# frozen_string_literal: true

# Autogenerated by fastlane
#
# Ensure this file is checked in to source control!

source 'https://gems.ruby-china.com/'

gem 'fastlane'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
