/*
 * Copyright (c) 2022 Institute of Software, Chinese Academy of Sciences (ISCAS)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#import "ESObject.h"
#import <Foundation/Foundation.h>

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

@protocol ESPairingBoxInfo
@end

@interface ESPairingBoxInfo : ESObject

/* 盒子端授权给客户端的凭证. [optional]
 */
@property (nonatomic) NSString *authKey;
/* 盒子端名称 [optional]
 */
@property (nonatomic) NSString *boxName;
/* 盒子端公钥. [optional]
 */
@property (nonatomic) NSString *boxPubKey;
/* 盒子端唯一id. [optional]
 */
@property (nonatomic) NSString *boxUuid;
/* 平台端授权给客户端的凭证. [optional]
 */
@property (nonatomic) NSString *regKey;
/* 盒子的唯一性域名(当前是盒子自动生成). [optional]
 */
@property (nonatomic) NSString *userDomain;

@property (nonatomic) NSString *spaceName;

@property (nonatomic) NSString *avatarUrl;
@property (nonatomic) NSString *aoId;

@end
