#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESABContact
@end

@interface ESABContact : ESObject


@property(nonatomic) NSString* address;

@property(nonatomic) NSString* email;

@property(nonatomic) NSString* firstName;

@property(nonatomic) NSString* image;

@property(nonatomic) NSString* lastName;

@property(nonatomic) NSString* middleName;

@property(nonatomic) NSString* telephone;

@property(nonatomic) NSString* userUID;

@end
