#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESAdminBindResult
@end

@interface ESAdminBindResult : ESObject

/* 用户错误码
 */
@property(nonatomic) NSString* code;

/* 用户aoId [optional]
 */
@property(nonatomic) NSString* aoId;
/* 随机32位密钥 [optional]
 */
@property(nonatomic) NSString* authKey;
/* boxname [optional]
 */
@property(nonatomic) NSString* boxName;
/* boxuuid [optional]
 */
@property(nonatomic) NSString* boxUuid;
/* 用户clientUUID [optional]
 */
@property(nonatomic) NSString* clientUUID;
/* client_regkey [optional]
 */
@property(nonatomic) NSString* regKey;
/* userdomain [optional]
 */
@property(nonatomic) NSString* userDomain;



@end
