#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "ESPublicKey.h"
#import "ESTransportation.h"
@protocol ESPublicKey;
@class ESPublicKey;
@protocol ESTransportation;
@class ESTransportation;



@protocol ESAlgorithmConfig
@end

@interface ESAlgorithmConfig : ESObject


@property(nonatomic) ESPublicKey* publicKey;

@property(nonatomic) ESTransportation* transportation;

@end
