#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESArticleRes
@end

@interface ESArticleRes : ESObject

/* 文章所在目录id [optional]
 */
@property(nonatomic) NSNumber* cataId;
/* 文章内容 [optional]
 */
@property(nonatomic) NSString* content;
/* 文章创建时间 [optional]
 */
@property(nonatomic) NSDate* createAt;
/* 文章id [optional]
 */
@property(nonatomic) NSNumber* _id;
/* 文章最后一次发布时间 [optional]
 */
@property(nonatomic) NSDate* publishdAt;
/* 文章状态：0-草稿;1-已发布 [optional]
 */
@property(nonatomic) NSNumber* state;
/* 文章标题 [optional]
 */
@property(nonatomic) NSString* title;
/* 文章上一次更新时间 [optional]
 */
@property(nonatomic) NSDate* updateAt;

@end
