#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESAuthorizedTerminalLoginConfirmInfo
@end

@interface ESAuthorizedTerminalLoginConfirmInfo : ESObject

/* 更新业务接口访问 token 的 token。 
 */
@property(nonatomic) NSString* accessToken;
/* 是否自动登录。 [optional]
 */
@property(nonatomic) NSNumber* autoLogin;
/* 对称密钥加密的clientuuid。 
 */
@property(nonatomic) NSString* encryptedClientUUID;
/* 是否允许登录。 [optional]
 */
@property(nonatomic) NSNumber* login;

@end
