#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESAuthorizedTerminalInfo
@end

@interface ESAuthorizedTerminalInfo : ESObject

/* 超时时间 [optional]
 */
@property(nonatomic) NSNumber* expireAt;
/* 授权终端类型 
 */
@property(nonatomic) NSString* terminalMode;
/* 用户userId 
 */
@property(nonatomic) NSString* userId;
/* 授权终端的uuid 
 */
@property(nonatomic) NSString* uuid;

@end
