#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESBackupStartReq
@end

@interface ESBackupStartReq : ESObject

@property(nonatomic) NSString* boxId;

@property(nonatomic) NSString* hint;

@property(nonatomic) NSString* backupDevice;

@property(nonatomic) NSString* backupDataType;

@property(nonatomic) NSNumber * mode;

@property(nonatomic) NSString * pass;

@end
