#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESBackupInfoRsp
@end

@interface ESBackupInfoRsp : ESObject


@property(nonatomic) NSString* boxId;

@property(nonatomic) NSNumber* endTime;

@property(nonatomic) NSString* msg;

@property(nonatomic) NSNumber* startTime;

@property(nonatomic) NSNumber* status;

@property(nonatomic) NSNumber* storageMoved;

@property(nonatomic) NSNumber* storageTotal;

@property(nonatomic) NSNumber* taskType;
/* 单位s [optional]
 */
@property(nonatomic) NSNumber* timeRemain;

@property(nonatomic) NSString* transId;

@end
