#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "ESNetworkClientInfo.h"
@protocol ESNetworkClientInfo;
@class ESNetworkClientInfo;



@protocol ESBoxInfo
@end

@interface ESBoxInfo : ESObject

/* 盒子的二维码数据. [optional]
 */
@property(nonatomic) NSString* boxQrCode;
/* 平台端授权给盒子端的凭证. [optional]
 */
@property(nonatomic) NSString* boxRegKey;

@property(nonatomic) NSNumber* boxRegisterTime;
/* 盒子端唯一id. [optional]
 */
@property(nonatomic) NSString* boxUuid;
/* 二维码中的蓝牙id. [optional]
 */
@property(nonatomic) NSString* btid;
/* mdns广播使用的id. [optional]
 */
@property(nonatomic) NSString* btidHash;

@property(nonatomic) NSNumber* isBoxRegistered;

@property(nonatomic) ESNetworkClientInfo* networkClient;

@end
