#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "ESBoxRegistryResultNetworkClient.h"
@protocol ESBoxRegistryResultNetworkClient;
@class ESBoxRegistryResultNetworkClient;



@protocol ESBoxRegistryResult
@end

@interface ESBoxRegistryResult : ESObject

/* 盒子的注册码，用于后续平台对于盒子访问合法性的验证 [optional]
 */
@property(nonatomic) NSString* boxRegKey;

@property(nonatomic) ESBoxRegistryResultNetworkClient* networkClient;

@end
