#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESCatalogueReq
@end

@interface ESCatalogueReq : ESObject

/* 目录名字 
 */
@property(nonatomic) NSString* cataName;
/* 父目录id 
 */
@property(nonatomic) NSNumber* parentId;

@end
