#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "ESAppletInfo.h"
@protocol ESAppletInfo;
@class ESAppletInfo;



@protocol ESCheckAppletResult
@end

@interface ESCheckAppletResult : ESObject


@property(nonatomic) ESAppletInfo* appletInfo;

@property(nonatomic) NSArray<NSString*>* categories;

@property(nonatomic) NSNumber* result;

@end
