#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "ESPackageRes.h"
@protocol ESPackageRes;
@class ESPackageRes;



@protocol ESCompatibleCheckRes
@end

@interface ESCompatibleCheckRes : ESObject

/* app是否需要强制更新 [optional]
 */
@property(nonatomic) NSNumber* isAppForceUpdate;
/* box是否需要强制更新 [optional]
 */
@property(nonatomic) NSNumber* isBoxForceUpdate;

@property(nonatomic) ESPackageRes* lastestAppPkg;

@property(nonatomic) ESPackageRes* lastestBoxPkg;

@end
