#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESCreateMemberInfo
@end

@interface ESCreateMemberInfo : ESObject

/* 客户端UUID（盒子公钥加密） 
 */
@property(nonatomic) NSString* clientUUID;
/* 邀请码（盒子公钥加密） 
 */
@property(nonatomic) NSString* inviteCode;
/* 昵称 不需要加密 
 */
@property(nonatomic) NSString* nickName;
/* 手机型号 不需要加密 
 */
@property(nonatomic) NSString* phoneModel;
/* 手机类型 不需要加密 [optional]
 */
@property(nonatomic) NSString* phoneType;

@property(nonatomic) NSString* applyEmail;

/* tempEncryptedSecret（盒子公钥加密） 
 */
@property(nonatomic) NSString* tempEncryptedSecret;

@end
