#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESCreateAuthCodeDTO
@end

@interface ESCreateAuthCodeDTO : ESObject

/* 使用对称密钥加密的授权码 (4 位数字)。 [optional]
 */
@property(nonatomic) NSString* authCode;
/* 使用对称密钥加密的 bkey, 盒子侧用的 key， 用来对应手机端和跳转后的盒子页面前端 [optional]
 */
@property(nonatomic) NSString* bkey;

@end
