#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "ESCreateMultipartTaskConflictRsp.h"
#import "ESCreateMultipartTaskSuccRsp.h"
#import "ESFileInfo.h"
@protocol ESCreateMultipartTaskConflictRsp;
@class ESCreateMultipartTaskConflictRsp;
@protocol ESCreateMultipartTaskSuccRsp;
@class ESCreateMultipartTaskSuccRsp;
@protocol ESFileInfo;
@class ESFileInfo;



@protocol ESCreateMultipartTaskRsp
@end

@interface ESCreateMultipartTaskRsp : ESObject

/* 秒传完成时的响应 [optional]
 */
@property(nonatomic) ESFileInfo* completeInfo;
/* 任务已存在时的响应 [optional]
 */
@property(nonatomic) ESCreateMultipartTaskConflictRsp* conflictInfo;
/* 返回类型，下面3个成员只有一个有效，其它为空 [optional]
 */
@property(nonatomic) NSNumber* rspType;
/* 成功创建任务时的响应 [optional]
 */
@property(nonatomic) ESCreateMultipartTaskSuccRsp* succInfo;

@end
