#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "ESAlgorithmConfig.h"
@protocol ESAlgorithmConfig;
@class ESAlgorithmConfig;



@protocol ESCreateMemberResult
@end

@interface ESCreateMemberResult : ESObject


@property(nonatomic) ESAlgorithmConfig* algorithmConfig;
/* 临时密钥加密后的 authKey [optional]
 */
@property(nonatomic) NSString* authKey;
/* 临时密钥加密后的 box uuid [optional]
 */
@property(nonatomic) NSString* boxUUID;
/* 网关返回状态码。 [optional]
 */
@property(nonatomic) NSString* code;
/* 返回消息。 [optional]
 */
@property(nonatomic) NSString* message;
/* 请求标识，用于跟踪业务请求过程。 [optional]
 */
@property(nonatomic) NSString* requestId;
/* 成员用户域名 [optional]
 */
@property(nonatomic) NSString* userDomain;

@end
