#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESDeviceTokenRes
@end

@interface ESDeviceTokenRes : ESObject

/* 盒子的 UUID [optional]
 */
@property(nonatomic) NSString* boxUUID;
/* 客户端的 UUID [optional]
 */
@property(nonatomic) NSString* clientUUID;
/* 创建时间 [optional]
 */
@property(nonatomic) NSDate* createAt;
/* 友盟 device token [optional]
 */
@property(nonatomic) NSString* deviceToken;
/* 设备类型,枚举值：android/ios/harmony [optional]
 */
@property(nonatomic) NSString* deviceType;
/* 扩展信息,json格式 [optional]
 */
@property(nonatomic) NSString* extra;
/* 更新时间 [optional]
 */
@property(nonatomic) NSDate* updateAt;
/* 用户的 ID [optional]
 */
@property(nonatomic) NSString* userId;

@end
