#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "ESEncryptAuthDTO.h"
@protocol ESEncryptAuthDTO;
@class ESEncryptAuthDTO;



@protocol ESEncryptAuthResult
@end

@interface ESEncryptAuthResult : ESObject


@property(nonatomic) NSNumber* code;

@property(nonatomic) ESEncryptAuthDTO* encryptAuthResult;

@property(nonatomic) NSString* message;

@property(nonatomic) NSString* requestId;

@end
