#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESEncryptAuthInfo
@end

@interface ESEncryptAuthInfo : ESObject

/* 盒子公钥加密的 authCode 
 */
@property(nonatomic) NSString* authCode;
/* 盒子公钥加密的 bkey 
 */
@property(nonatomic) NSString* bkey;
/* 盒子公钥加密的 clientUUID [optional]
 */
@property(nonatomic) NSString* clientUUID;
/* 客户端类型 [optional]
 */
@property(nonatomic) NSString* terminalMode;

@property(nonatomic) NSString* terminalType;
/* 盒子公钥加密的 临时密钥 
 */
@property(nonatomic) NSString* tmpEncryptedSecret;

@end
