#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESFeedbackRes
@end

@interface ESFeedbackRes : ESObject

/* 行动 [optional]
 */
@property(nonatomic) NSString* action;
/* 推送时间 [optional]
 */
@property(nonatomic) NSString* createdAt;
/* uuid [optional]
 */
@property(nonatomic) NSString* _id;
/* 对象 [optional]
 */
@property(nonatomic) NSString* object;

@end
