#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESFeedbackPayloadReq
@end

@interface ESFeedbackPayloadReq : ESObject

/* 用户的回答详情 [optional]
 */
@property(nonatomic) NSObject* answer;
/* 答案ID [optional]
 */
@property(nonatomic) NSNumber* answerId;
/* 用户提交答案的时间 [optional]
 */
@property(nonatomic) NSString* endedAt;
/* 自定义信息  [optional]
 */
@property(nonatomic) NSString* openid;
/* 用户开始回答的时间 [optional]
 */
@property(nonatomic) NSString* startedAt;
/* 问卷ID [optional]
 */
@property(nonatomic) NSNumber* surveyId;

@end
