#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESFileInfoPub
@end

@interface ESFileInfoPub : ESObject


@property(nonatomic) NSString* betag;

@property(nonatomic) NSString* category;

@property(nonatomic) NSNumber* createdAt;

@property(nonatomic) NSNumber* fileCount;

@property(nonatomic) NSNumber* isDir;

@property(nonatomic) NSString* mime;

@property(nonatomic) NSNumber* modifyAt;

@property(nonatomic) NSString* name;

@property(nonatomic) NSNumber* operationAt;

@property(nonatomic) NSString* parentUuid;

@property(nonatomic) NSString* path;

@property(nonatomic) NSNumber* size;

@property(nonatomic) NSNumber* trashed;

@property(nonatomic) NSString* uuid;

@property(nonatomic) NSNumber* duration;

@property(nonatomic,assign) BOOL isSelected;

@property(nonatomic) NSString* searchKey;

@end
