#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESGenPkeyRsp
@end

@interface ESGenPkeyRsp : ESObject

/* pkey有效时间 [optional]
 */
@property(nonatomic) NSDate* expiresAt;
/* 二维码pkey值 [optional]
 */
@property(nonatomic) NSString* pkey;

@end
