#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESGetAccessTokenRequest
@end

@interface ESGetAccessTokenRequest : ESObject

/* 当前小应用 id [optional]
 */
@property(nonatomic) NSString* appletId;
/* 盒子公钥加密的授权码 [optional]
 */
@property(nonatomic) NSString* encryptedAuthCode;
/* 盒子公钥加密的 clientUUID [optional]
 */
@property(nonatomic) NSString* encryptedClientUUID;
/* 盒子公钥加密的临时对称密钥 [optional]
 */
@property(nonatomic) NSString* tempEncryptedSecret;
/* 当前用户 id [optional]
 */
@property(nonatomic) NSString* userId;

@end
