#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "ESBoxInfo.h"
@protocol ESBoxInfo;
@class ESBoxInfo;



@protocol ESInfo
@end

@interface ESInfo : ESObject


@property(nonatomic) ESBoxInfo* boxInfo;
/* TheClientInfo     *ClientInfo `json:\"clientInfo\"` [optional]
 */
@property(nonatomic) NSString* boxPriKeyBytes;

@property(nonatomic) NSString* boxPublicKey;
/* Docker是否已经初始化完成 [optional]
 */
@property(nonatomic) NSNumber* dockerStatus;
/* 是否已经初始化 [optional]
 */
@property(nonatomic) NSNumber* isBoxInit;
/* 是否已经配对 [optional]
 */
@property(nonatomic) NSNumber* isClientPaired;
/* 状态 [optional]
 */
@property(nonatomic) NSString* status;
/* 客户端版本 [optional]
 */
@property(nonatomic) NSString* version;

@end
