#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESInviteResult
@end

@interface ESInviteResult : ESObject

/* 盒子公钥。 [optional]
 */
@property(nonatomic) NSString* boxPublicKey;
/* 网关返回状态码。 [optional]
 */
@property(nonatomic) NSString* code;
/* 返回消息。 [optional]
 */
@property(nonatomic) NSString* message;
/* 请求标识，用于跟踪业务请求过程。 [optional]
 */
@property(nonatomic) NSString* requestId;

@end
