#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESKeyExchangeReq
@end

@interface ESKeyExchangeReq : ESObject

/* 必填,客户端对称密钥种子 [optional]
 */
@property(nonatomic) NSString* clientPreSecret;
/* 必填,使用盒子端公钥加密btid后进行base64得到的字符串 [optional]
 */
@property(nonatomic) NSString* encBtid;

@end
