#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESKeyExchangeRsp
@end

@interface ESKeyExchangeRsp : ESObject

/* iv. [optional]
 */
@property(nonatomic) NSString* iv;
/* 对称密钥. [optional]
 */
@property(nonatomic) NSString* sharedSecret;

@end
