#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESMemberCreateInfo
@end

@interface ESMemberCreateInfo : ESObject

/* 用户绑定盒子clientUUID 
 */
@property(nonatomic) NSString* clientUUID;
/* 用户绑定盒子邀请码 
 */
@property(nonatomic) NSString* inviteCode;
/* 用户昵称 
 */
@property(nonatomic) NSString* nickName;
/* 绑定手机的型号 
 */
@property(nonatomic) NSString* phoneModel;

@end
