#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "ESBoxRegistryResultNetworkClient.h"
@protocol ESBoxRegistryResultNetworkClient;
@class ESBoxRegistryResultNetworkClient;



@protocol ESMessagePayload
@end

@interface ESMessagePayload : ESObject


@property(nonatomic) ESBoxRegistryResultNetworkClient* body;
/* 消息类型，枚举：notification-通知/message-消息 
 */
@property(nonatomic) NSString* displayType;
/* 可选，Map格式，用户自定义key-value [optional]
 */
@property(nonatomic) NSDictionary<NSString*, NSString*>* extra;

@end
