#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESMemberUsedStorageResult
@end

@interface ESMemberUsedStorageResult : ESObject

/* 返回码 [optional]
 */
@property(nonatomic) NSString* code;
/* message信息 [optional]
 */
@property(nonatomic) NSString* message;
/* requestId [optional]
 */
@property(nonatomic) NSString* requestId;
/* 用户 [optional]
 */
@property(nonatomic) NSDictionary<NSString*, NSString*>* results;

@end
