#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESModifyFileReq
@end

@interface ESModifyFileReq : ESObject

/* 新文件名 [optional]
 */
@property(nonatomic) NSString* fileName;
/* 文件的uuid [optional]
 */
@property(nonatomic) NSString* uuid;

@end
