#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "ESMyShareRsp.h"
#import "ESPageInfoExt.h"
@protocol ESMyShareRsp;
@class ESMyShareRsp;
@protocol ESPageInfoExt;
@class ESPageInfoExt;



@protocol ESMyShareListRsp
@end

@interface ESMyShareListRsp : ESObject


@property(nonatomic) ESPageInfoExt* pageInfo;

@property(nonatomic) NSArray<ESMyShareRsp>* shareList;

@end
