#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESNetworkServerRes
@end

@interface ESNetworkServerRes : ESObject

/* 透传服务器地址 [optional]
 */
@property(nonatomic) NSString* serverAddress;
/* stun服务器地址 [optional]
 */
@property(nonatomic) NSString* stunAddress;

@end
