#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESNetworkAuthReq
@end

@interface ESNetworkAuthReq : ESObject

/* network client id 
 */
@property(nonatomic) NSString* clientId;
/* network client 访问密钥 
 */
@property(nonatomic) NSString* secretKey;

@end
