#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESOAuthProcessData
@end

@interface ESOAuthProcessData : ESObject

/* 小应用 id [optional]
 */
@property(nonatomic) NSString* appletId;
/* 当前授权码 [optional]
 */
@property(nonatomic) NSString* authCode;
/* 服务权限分组，包括其具体的权限列表 [optional]
 */
@property(nonatomic) NSDictionary<NSString*, NSArray<NSString*>*>* categories;
/* 该授权码失效实际：采用自 1970-01-01T00:00:00Z 以来的秒数 [optional]
 */
@property(nonatomic) NSNumber* expiresIn;
/* 当前用户 id [optional]
 */
@property(nonatomic) NSString* userId;

@end
