#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "ESPageInfo.h"
#import "ESReservedDomainInfo.h"
@protocol ESPageInfo;
@class ESPageInfo;
@protocol ESReservedDomainInfo;
@class ESReservedDomainInfo;



@protocol ESPageListResultReservedDomainInfo
@end

@interface ESPageListResultReservedDomainInfo : ESObject


@property(nonatomic) NSArray<ESReservedDomainInfo>* list;

@property(nonatomic) ESPageInfo* pageInfo;

@end
