#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESPairingReq
@end

@interface ESPairingReq : ESObject

/* 客户端手机型号. [optional]
 */
@property(nonatomic) NSString* clientPhoneModel;
/* 客户端私钥. [optional]
 */
@property(nonatomic) NSString* clientPriKey;
/* 客户端公钥. [optional]
 */
@property(nonatomic) NSString* clientPubKey;
/* 客户端唯一id. [optional]
 */
@property(nonatomic) NSString* clientUuid;

@end
