#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "ESPageInfo.h"
#import "ESProposalRes.h"
@protocol ESPageInfo;
@class ESPageInfo;
@protocol ESProposalRes;
@class ESProposalRes;



@protocol ESPageListResultProposalRes
@end

@interface ESPageListResultProposalRes : ESObject


@property(nonatomic) NSArray<ESProposalRes>* list;

@property(nonatomic) ESPageInfo* pageInfo;

@end
