#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESPersonalInfo
@end

@interface ESPersonalInfo : ESObject


@property(nonatomic) NSString* aoId;
/* 用户名 [optional]
 */
@property(nonatomic) NSString* personalName;
/* 用户签名 [optional]
 */
@property(nonatomic) NSString* personalSign;

@property(nonatomic) NSString* phoneModel;

@property(nonatomic) NSString* userDomain;

@end
