#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESProposalRes
@end

@interface ESProposalRes : ESObject

/* 反馈内容 [optional]
 */
@property(nonatomic) NSString* content;
/* 邮箱 [optional]
 */
@property(nonatomic) NSString* email;
/* 反馈时间 [optional]
 */
@property(nonatomic) NSDate* feedbackAt;
/* 图片地址 [optional]
 */
@property(nonatomic) NSArray<NSString*>* imageUrls;
/* 手机号码 [optional]
 */
@property(nonatomic) NSString* phoneNumber;
/* id [optional]
 */
@property(nonatomic) NSNumber* proposalId;
/* 用户域名 [optional]
 */
@property(nonatomic) NSString* userDomain;

@end
