#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol ESProposalReq
@end

@interface ESProposalReq : ESObject

/* 反馈内容 
 */
@property(nonatomic) NSString* content;
/* 邮箱 [optional]
 */
@property(nonatomic) NSString* email;
/* 图片地址 [optional]
 */
@property(nonatomic) NSArray<NSString*>* imageUrls;
/* 电话号码 [optional]
 */
@property(nonatomic) NSString* phoneNumber;


@property(nonatomic) NSString* boxUUID;

@property(nonatomic) NSString* userId;

@end
