#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "ESBoxRegistryResultNetworkClient.h"
#import "ESUserIdAndClientUUID.h"
@protocol ESBoxRegistryResultNetworkClient;
@class ESBoxRegistryResultNetworkClient;
@protocol ESUserIdAndClientUUID;
@class ESUserIdAndClientUUID;



@protocol ESPushMessage
@end

@interface ESPushMessage : ESObject

/* 盒子的注册码 
 */
@property(nonatomic) NSString* boxRegKey;
/* 盒子的 UUID 
 */
@property(nonatomic) NSString* boxUUID;

@property(nonatomic) ESBoxRegistryResultNetworkClient* channelProperties;
/* 客户端的 UUID列表,当type=client_cast时,必填 [optional]
 */
@property(nonatomic) NSArray<ESUserIdAndClientUUID>* clientUUIDs;
/* 发送消息描述,可选 [optional]
 */
@property(nonatomic) NSString* _description;

@property(nonatomic) ESBoxRegistryResultNetworkClient* payload;

@property(nonatomic) ESBoxRegistryResultNetworkClient* policy;
/* 消息发送类型,枚举值：clientcast-推送目标设备/broadcast-广播 
 */
@property(nonatomic) NSString* type;
/* 用户的 ID列表,当type=user_cast时,必填 [optional]
 */
@property(nonatomic) NSArray<NSString*>* userIds;

@end
