#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESPubKeyExchangeRsp
@end

@interface ESPubKeyExchangeRsp : ESObject

/* 盒子端公钥. [optional]
 */
@property(nonatomic) NSString* boxPubKey;
/* 用盒子端端私钥签名btid. 客户端用盒子端公钥进行验证. [optional]
 */
@property(nonatomic) NSString* signedBtid;

@end
