#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESPubKeyExchangeReq
@end

@interface ESPubKeyExchangeReq : ESObject

/* 客户端私钥. [optional]
 */
@property(nonatomic) NSString* clientPriKey;
/* 客户端公钥. [optional]
 */
@property(nonatomic) NSString* clientPubKey;
/* 用客户端私钥签名btid. 盒子端用客户端公钥进行验证. [optional]
 */
@property(nonatomic) NSString* signedBtid;

@end
