#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESQuestionnaireRes
@end

@interface ESQuestionnaireRes : ESObject

/* 问卷链接 [optional]
 */
@property(nonatomic) NSString* content;
/* 结束时间 [optional]
 */
@property(nonatomic) NSDate* endAt;
/* 已反馈数量 [optional]
 */
@property(nonatomic) NSNumber* feedbackStatistic;
/* 第三方问卷id [optional]
 */
@property(nonatomic) NSNumber* payloadSurveyId;
/* 问卷id [optional]
 */
@property(nonatomic) NSNumber* questionnaireId;
/* 开始时间 [optional]
 */
@property(nonatomic) NSDate* startAt;
/* 问卷状态，携带用户信息查询时返回 [optional]
 */
@property(nonatomic) NSString* state;
/* 标题 [optional]
 */
@property(nonatomic) NSString* title;

@end
