#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESRevokeClientResult
@end

@interface ESRevokeClientResult : ESObject

/* 是否成功标记，true：成功，false：失败。 [optional]
 */
@property(nonatomic) NSNumber* succeed;

@end
