#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESRefreshTokenInfo
@end

@interface ESRefreshTokenInfo : ESObject

/* 更新业务接口访问 token 的 token。 
 */
@property(nonatomic) NSString* refreshToken;

@end
