#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESReservedDomainMatchInfo
@end

@interface ESReservedDomainMatchInfo : ESObject

/* 全局唯一的 subdomain [optional]
 */
@property(nonatomic) NSString* subdomain;
/* 更新时间 [optional]
 */
@property(nonatomic) NSDate* updatedAt;

@end
