#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESRefreshTokenRequest
@end

@interface ESRefreshTokenRequest : ESObject

/* 刷新 token [optional]
 */
@property(nonatomic) NSString* refreshToken;
/* 临时交互密钥，通过盒子公钥加密 [optional]
 */
@property(nonatomic) NSString* tempEncryptedSecret;

@end
