#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "ESFileInfoPub.h"
#import "ESPageInfoExt.h"
@protocol ESFileInfoPub;
@class ESFileInfoPub;
@protocol ESPageInfoExt;
@class ESPageInfoExt;



@protocol ESShareContentRsp
@end

@interface ESShareContentRsp : ESObject

/* 文件列表 [optional]
 */
@property(nonatomic) NSArray<ESFileInfoPub>* fileList;

@property(nonatomic) NSString* image;

@property(nonatomic) NSString* name;

@property(nonatomic) ESPageInfoExt* pageInfo;
/* 用户id，用户昵称，头像 [optional]
 */
@property(nonatomic) NSString* personalName;

@property(nonatomic) NSNumber* secondLeft;

@end
