#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESStartDownRes
@end

@interface ESStartDownRes : ESObject

/* 重新下载：当已经有任务在下载的时候，用户仍然想重新开始下载，使用此选项 [optional]
 */
@property(nonatomic) NSNumber* anew;

@property(nonatomic) NSString* versionId;

@end
