#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESTransBoxInfoReq
@end

@interface ESTransBoxInfoReq : ESObject

/* 盒子侧bkey值 
 */
@property(nonatomic) NSString* bkey;
/* 盒子公钥 
 */
@property(nonatomic) NSString* boxPubKey;
/* 二维码pkey值 
 */
@property(nonatomic) NSString* pkey;
/* 用户域名 
 */
@property(nonatomic) NSString* userDomain;

@end
