#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESTransportation
@end

@interface ESTransportation : ESObject


@property(nonatomic) NSString* algorithm;
/* base64 编码后的 16位字节数组 initializationVector [optional]
 */
@property(nonatomic) NSString* initializationVector;

@property(nonatomic) NSNumber* keySize;

@property(nonatomic) NSString* transformation;

@end
