#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "ESClientRegistryDetailInfo.h"
@protocol ESClientRegistryDetailInfo;
@class ESClientRegistryDetailInfo;



@protocol ESUserRegistryDetailInfo
@end

@interface ESUserRegistryDetailInfo : ESObject

/* client相关信息 [optional]
 */
@property(nonatomic) NSArray<ESClientRegistryDetailInfo>* clientInfos;
/* 创建时间 [optional]
 */
@property(nonatomic) NSDate* createdAt;
/* 子域名 [optional]
 */
@property(nonatomic) NSString* subDomain;
/* 为用户分配的用户域名，该域名可以用于后续的业务访问 [optional]
 */
@property(nonatomic) NSString* userDomain;
/* 用户id [optional]
 */
@property(nonatomic) NSString* userId;
/* 注册类型 [optional]
 */
@property(nonatomic) NSString* userType;

@end
