#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESUserRegistryInfo
@end

@interface ESUserRegistryInfo : ESObject

/* 盒子的注册码 
 */
@property(nonatomic) NSString* boxRegKey;
/* 盒子的 UUID 
 */
@property(nonatomic) NSString* boxUUID;
/* 客户端的 UUID 
 */
@property(nonatomic) NSString* clientUUID;
/* 用户被指定的子域名字段 [optional]
 */
@property(nonatomic) NSString* subdomain;
/* 用户的 ID 
 */
@property(nonatomic) NSString* userId;
/* 用户类型（管理员、普通成员），取值：user_admin、user_member 
 */
@property(nonatomic) NSString* userType;

@end
