#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESUserRegistryResult
@end

@interface ESUserRegistryResult : ESObject

/* 客户端的注册码，用于后续平台对于客户端访问合法性的验证 [optional]
 */
@property(nonatomic) NSString* clientRegKey;
/* 为用户分配的用户域名，该域名可以用于后续的业务访问 [optional]
 */
@property(nonatomic) NSString* userDomain;
/* 用户的注册码，用于后续平台对于用户访问合法性的验证 [optional]
 */
@property(nonatomic) NSString* userRegKey;

@end
