#import <Foundation/Foundation.h>
#import "ESObject.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol ESWifiStatusRsp
@end

@interface ESWifiStatusRsp : ESObject


@property(nonatomic) NSString* addr;

@property(nonatomic) NSArray<NSString*>* ipAddress;

@property(nonatomic) NSString* name;

@property(nonatomic) NSNumber* status;

@end
