/*
 * Copyright (c) 2022 Institute of Software, Chinese Academy of Sciences (ISCAS)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED CODE - DO NOT MODIFY BY HAND
// @see sync_images.sh
// #import "ESImageDefine.h"

#ifndef ESImageDefine_h
#define ESImageDefine_h

#import <UIKit/UIKit.h>

#define IMAGE_APP_LOGO [UIImage imageNamed:@"app_logo"]
#define IMAGE_BIND_BLE_FAILED [UIImage imageNamed:@"bind_ble_failed"]
#define IMAGE_BOX_BIND_FAIL [UIImage imageNamed:@"box_bind_fail"]
#define IMAGE_BOX_BIND_SUCCESS [UIImage imageNamed:@"box_bind_success"]
#define IMAGE_BOX_INFO_BG [UIImage imageNamed:@"box_info_bg"]
#define IMAGE_BOX_LIST_DISMISS [UIImage imageNamed:@"box_list_dismiss"]
#define IMAGE_BOX_LOGO [UIImage imageNamed:@"box_logo"]
#define IMAGE_BOX_SCAN_PROMPT_BIND_CONFIRM [UIImage imageNamed:@"box_scan_prompt_bind_confirm"]
#define IMAGE_BOX_SCAN_PROMPT_BLUETOOTH_ON [UIImage imageNamed:@"box_scan_prompt_bluetooth_on"]
#define IMAGE_BOX_SCAN_PROMPT_POWER_ON [UIImage imageNamed:@"box_scan_prompt_power_on"]
#define IMAGE_BOX_SCAN_PROMPT_SCAN_QRCODE [UIImage imageNamed:@"box_scan_prompt_scan_qrcode"]
#define IMAGE_BOX_SPACE_SIZE_BG [UIImage imageNamed:@"box_space_size_bg"]
#define IMAGE_CLOUD_IMAGE_DEFAULT [UIImage imageNamed:@"photo_default"]
#define IMAGE_COMMON_CLOSE [UIImage imageNamed:@"common_close"]
#define IMAGE_COMMON_GRADUAL_BTNBG [UIImage imageNamed:@"common_gradual_btnbg"]
#define IMAGE_DISMISS [UIImage imageNamed:@"dismiss"]
#define IMAGE_DROPDOWNFLAG [UIImage imageNamed:@"dropdownFlag"]
#define IMAGE_EMPTY_BG [UIImage imageNamed:@"empty_bg"]
#define IMAGE_EMPTY_NOFILE [UIImage imageNamed:@"empty_noFile"]
#define IMAGE_EMPTY_NO_BOX [UIImage imageNamed:@"empty_no_box"]
#define IMAGE_EMPTY_NO_FOLDER [UIImage imageNamed:@"empty_no_folder"]
#define IMAGE_EMPTY_NO_IMAGE [UIImage imageNamed:@"empty_no_image"]
#define IMAGE_EMPTY_NO_NETWORK [UIImage imageNamed:@"empty_no_network"]
#define IMAGE_EMPTY_NO_NEWS [UIImage imageNamed:@"empty_no_news"]
#define IMAGE_EMPTY_NO_OPERATION_RECORD [UIImage imageNamed:@"empty_no_operation_record"]
#define IMAGE_EMPTY_NO_TRANSFER [UIImage imageNamed:@"empty_no_transfer"]
#define IMAGE_FEEDBACK_SUBMITTED [UIImage imageNamed:@"feedback_submitted"]
#define IMAGE_FILE_BOTTOM_COPY [UIImage imageNamed:@"file_bottom_copy"]
#define IMAGE_FILE_BOTTOM_DEL [UIImage imageNamed:@"file_bottom_del"]
#define IMAGE_FILE_BOTTOM_DETAILS [UIImage imageNamed:@"file_bottom_details"]
#define IMAGE_FILE_BOTTOM_DOWN [UIImage imageNamed:@"file_bottom_down"]
#define IMAGE_FILE_BOTTOM_MORE [UIImage imageNamed:@"file_bottom_more"]
#define IMAGE_FILE_BOTTOM_MOVE [UIImage imageNamed:@"file_bottom_move"]
#define IMAGE_FILE_BOTTOM_SHARE [UIImage imageNamed:@"file_bottom_share"]
#define IMAGE_FILE_COPYBACK [UIImage imageNamed:@"file_copyback"]
#define IMAGE_FILE_DOWNLOAD [UIImage imageNamed:@"file_download"]
#define IMAGE_FILE_FLOAT_UPLOAD [UIImage imageNamed:@"file_float_upload"]
#define IMAGE_FILE_FOLDER [UIImage imageNamed:@"file_folder"]
#define IMAGE_FILE_HEADER_EXPAND [UIImage imageNamed:@"file_header_expand"]
#define IMAGE_FILE_NEWFOLDER [UIImage imageNamed:@"file_newfolder"]
#define IMAGE_FILE_PAUSE [UIImage imageNamed:@"file_pause"]
#define IMAGE_FILE_RENAME [UIImage imageNamed:@"file_rename"]
#define IMAGE_FILE_RETRY [UIImage imageNamed:@"file_retry"]
#define IMAGE_FILE_SELECTED [UIImage imageNamed:@"file_selected"]
#define IMAGE_FILE_SELECTED_ICON [UIImage imageNamed:@"file_selected_icon"]
#define IMAGE_FILE_SORT_CLASS [UIImage imageNamed:@"file_sort_class"]
#define IMAGE_FILE_SORT_CLASS_SELECTED [UIImage imageNamed:@"file_sort_class_selected"]
#define IMAGE_FILE_SORT_DOWN [UIImage imageNamed:@"file_sort_down"]
#define IMAGE_FILE_SORT_NAME [UIImage imageNamed:@"file_sort_name"]
#define IMAGE_FILE_SORT_NAME_SELECTED [UIImage imageNamed:@"file_sort_name_selected"]
#define IMAGE_FILE_SORT_UP [UIImage imageNamed:@"file_sort_up"]
#define IMAGE_FILE_SYNC_DONE [UIImage imageNamed:@"file_sync_done"]
#define IMAGE_FILE_TITLE_MENU [UIImage imageNamed:@"file_title_menu"]
#define IMAGE_FILE_TYPE_AI [UIImage imageNamed:@"file_type_ai"]
#define IMAGE_FILE_TYPE_AUDIO [UIImage imageNamed:@"file_type_audio"]
#define IMAGE_FILE_TYPE_EXCEL [UIImage imageNamed:@"file_type_excel"]
#define IMAGE_FILE_TYPE_HTML [UIImage imageNamed:@"file_type_html"]
#define IMAGE_FILE_TYPE_IMAGE [UIImage imageNamed:@"file_type_image"]
#define IMAGE_FILE_TYPE_PDF [UIImage imageNamed:@"file_type_pdf"]
#define IMAGE_FILE_TYPE_PPT [UIImage imageNamed:@"file_type_ppt"]
#define IMAGE_FILE_TYPE_PSD [UIImage imageNamed:@"file_type_psd"]
#define IMAGE_FILE_TYPE_RAR [UIImage imageNamed:@"file_type_rar"]
#define IMAGE_FILE_TYPE_TEXT [UIImage imageNamed:@"file_type_text"]
#define IMAGE_FILE_TYPE_TORRENT [UIImage imageNamed:@"file_type_torrent"]
#define IMAGE_FILE_TYPE_VIDEO [UIImage imageNamed:@"file_type_video"]
#define IMAGE_FILE_TYPE_WEIZHI [UIImage imageNamed:@"file_type_weizhi"]
#define IMAGE_FILE_TYPE_WORD [UIImage imageNamed:@"file_type_word"]
#define IMAGE_FILE_UNSELECTED [UIImage imageNamed:@"file_unselected"]
#define IMAGE_FILE_UPLOAD [UIImage imageNamed:@"file_upload"]
#define IMAGE_FILE_UPLOAD_DOCUMENT [UIImage imageNamed:@"file_upload_document"]
#define IMAGE_FILE_UPLOAD_IMAGE [UIImage imageNamed:@"file_upload_image"]
#define IMAGE_FILE_UPLOAD_VIDEO [UIImage imageNamed:@"file_upload_video"]
#define IMAGE_GUIDE_PAGE1 [UIImage imageNamed:@"guide_page1"]
#define IMAGE_GUIDE_PAGE1_EN [UIImage imageNamed:@"guide_page1_en"]
#define IMAGE_GUIDE_PAGE2 [UIImage imageNamed:@"guide_page2"]
#define IMAGE_GUIDE_PAGE2_EN [UIImage imageNamed:@"guide_page2_en"]
#define IMAGE_GUIDE_PAGE3 [UIImage imageNamed:@"guide_page3"]
#define IMAGE_GUIDE_PAGE3_EN [UIImage imageNamed:@"guide_page3_en"]
#define IMAGE_GUIDE_SMALL_PAGE1 [UIImage imageNamed:@"guide_small_page1"]
#define IMAGE_GUIDE_SMALL_PAGE2 [UIImage imageNamed:@"guide_small_page2"]
#define IMAGE_GUIDE_SMALL_PAGE3 [UIImage imageNamed:@"guide_small_page3"]
#define IMAGE_IC_BACK_CHEVRON [UIImage imageNamed:@"ic_back_chevron"]
#define IMAGE_IC_SCAN_LINE [UIImage imageNamed:@"ic_scan_line"]
#define IMAGE_INITIALIZATION_PRGRESSS [UIImage imageNamed:@"initialization_prgresss"]
#define IMAGE_LOCAL_NETWORKING_ACCESS [UIImage imageNamed:@"local_networking_access"]
#define IMAGE_LOGIN_ANDROID [UIImage imageNamed:@"login_android"]
#define IMAGE_LOGIN_AUTO [UIImage imageNamed:@"login_auto"]
#define IMAGE_LOGIN_AUTO_SED [UIImage imageNamed:@"login_auto_sed"]
#define IMAGE_LOGIN_BIND [UIImage imageNamed:@"login_bind"]
#define IMAGE_LOGIN_BIND_ICON [UIImage imageNamed:@"login_bind_icon"]
#define IMAGE_LOGIN_BIND_ICON_SED [UIImage imageNamed:@"login_bind_icon_sed"]
#define IMAGE_LOGIN_BIND_SED [UIImage imageNamed:@"login_bind_sed"]
#define IMAGE_LOGIN_DANGQIAN [UIImage imageNamed:@"login_dangqian"]
#define IMAGE_LOGIN_EFFICACY [UIImage imageNamed:@"login_efficacy"]
#define IMAGE_LOGIN_EMPOWER [UIImage imageNamed:@"login_empower"]
#define IMAGE_LOGIN_EMPOWER_SED [UIImage imageNamed:@"login_empower_sed"]
#define IMAGE_LOGIN_IOS [UIImage imageNamed:@"login_ios"]
#define IMAGE_LOGIN_LIULANQI [UIImage imageNamed:@"login_liulanqi"]
#define IMAGE_LOGIN_TERMINAL [UIImage imageNamed:@"login_terminal"]
#define IMAGE_LOGIN_UNKNOW [UIImage imageNamed:@"login_unknow"]
#define IMAGE_MAILBOX_UNREAD [UIImage imageNamed:@"mailbox_unread"]
#define IMAGE_MAIN_ADDRESSLIST [UIImage imageNamed:@"main_addresslist"]
#define IMAGE_MAIN_ALBUM [UIImage imageNamed:@"main_album"]
#define IMAGE_MAIN_CAROUSE_LAN [UIImage imageNamed:@"main_carouse_lan"]
#define IMAGE_MAIN_CAROUSE_LAN_EN [UIImage imageNamed:@"main_carouse_lan_en"]
#define IMAGE_MAIN_FILE [UIImage imageNamed:@"main_file"]
#define IMAGE_MAIN_HELP [UIImage imageNamed:@"main_help"]
#define IMAGE_MAIN_HELP_EN [UIImage imageNamed:@"main_help_en"]
#define IMAGE_MAIN_HELP_RETURN [UIImage imageNamed:@"main_help_return"]
#define IMAGE_MAIN_ICON [UIImage imageNamed:@"main_icon"]
#define IMAGE_MAIN_IDEA [UIImage imageNamed:@"main_idea"]
#define IMAGE_MAIN_IDEA_RETURN [UIImage imageNamed:@"main_idea_return"]
#define IMAGE_MAIN_MESHARE [UIImage imageNamed:@"main_meshare"]
#define IMAGE_MAIN_NEWHAND [UIImage imageNamed:@"main_newhand"]
#define IMAGE_MAIN_NEWHAND_EN [UIImage imageNamed:@"main_newhand_en"]
#define IMAGE_MAIN_OTHER [UIImage imageNamed:@"main_other"]
#define IMAGE_MAIN_PHOTO [UIImage imageNamed:@"main_photo"]
#define IMAGE_MAIN_PUSH_NEWS_BG [UIImage imageNamed:@"main_push_news_bg"]
#define IMAGE_MAIN_QRCODE [UIImage imageNamed:@"main_qrcode"]
#define IMAGE_MAIN_RECYCLEBIN [UIImage imageNamed:@"main_recyclebin"]
#define IMAGE_MAIN_ROTATE_INTERNET [UIImage imageNamed:@"main_rotate_Internet"]
#define IMAGE_MAIN_ROTATE_LAN [UIImage imageNamed:@"main_rotate_LAN"]
#define IMAGE_MAIN_SEARCH [UIImage imageNamed:@"main_search"]
#define IMAGE_MAIN_SORT [UIImage imageNamed:@"main_sort"]
#define IMAGE_MAIN_SORT_TIME [UIImage imageNamed:@"main_sort_time"]
#define IMAGE_MAIN_SORT_TIME_SELECTED [UIImage imageNamed:@"main_sort_time_selected"]
#define IMAGE_MAIN_TRANSFER [UIImage imageNamed:@"main_transfer"]
#define IMAGE_MAIN_TRANSFER_INTERNET [UIImage imageNamed:@"main_transfer_Internet"]
#define IMAGE_MAIN_TRANSFER_LAN [UIImage imageNamed:@"main_transfer_lan"]
#define IMAGE_MAIN_TRY [UIImage imageNamed:@"main_try"]
#define IMAGE_MAIN_TRY_HELP [UIImage imageNamed:@"main_try_help"]
#define IMAGE_MAIN_VIDEO [UIImage imageNamed:@"main_video"]
#define IMAGE_ME_ABOUT [UIImage imageNamed:@"me_about"]
#define IMAGE_ME_ALBUM_SYNC [UIImage imageNamed:@"me_album_sync"]
#define IMAGE_ME_ARROW [UIImage imageNamed:@"me_arrow"]
#define IMAGE_ME_AVATAR_DEFAULT [UIImage imageNamed:@"me_avatar_default"]
#define IMAGE_ME_BACKUP_AND_RESTORE [UIImage imageNamed:@"me_backup_and_restore"]
#define IMAGE_ME_BACKUP_FAIL [UIImage imageNamed:@"me_backup_fail"]
#define IMAGE_ME_BACKUP_HEADIMAGE [UIImage imageNamed:@"me_backup_headimage"]
#define IMAGE_ME_BACKUP_HEADIMAGEBG [UIImage imageNamed:@"me_backup_headimagebg"]
#define IMAGE_ME_BACKUP_LOADING [UIImage imageNamed:@"me_backup_loading"]
#define IMAGE_ME_BACKUP_REFRESH [UIImage imageNamed:@"me_backup_refresh"]
#define IMAGE_ME_BACKUP_SUCCESS [UIImage imageNamed:@"me_backup_success"]
#define IMAGE_ME_CACHE [UIImage imageNamed:@"me_cache"]
#define IMAGE_ME_COPY [UIImage imageNamed:@"me_copy"]
#define IMAGE_ME_DEVICE_MANAGE [UIImage imageNamed:@"me_device_manage"]
#define IMAGE_ME_FAMILY_ADD [UIImage imageNamed:@"me_family_add"]
#define IMAGE_ME_FAMILY_ADMIN [UIImage imageNamed:@"me_family_admin"]
#define IMAGE_ME_FAMILY_CELL_BG [UIImage imageNamed:@"me_family_cell_bg"]
#define IMAGE_ME_FAMILY_INVITE [UIImage imageNamed:@"me_family_invite"]
#define IMAGE_ME_FAMILY_INVITE_LINK [UIImage imageNamed:@"me_family_invite_link"]
#define IMAGE_ME_FAMILY_INVITE_VX [UIImage imageNamed:@"me_family_invite_vx"]
#define IMAGE_ME_FAMILY_MYSELF [UIImage imageNamed:@"me_family_myself"]
#define IMAGE_ME_FAQ [UIImage imageNamed:@"me_faq"]
#define IMAGE_ME_LOGO [UIImage imageNamed:@"me_logo"]
#define IMAGE_ME_MANAGEMENT_ICON [UIImage imageNamed:@"me_management_icon"]
#define IMAGE_ME_MEMBER [UIImage imageNamed:@"me_member"]
#define IMAGE_ME_NEWS [UIImage imageNamed:@"me_news"]
#define IMAGE_ME_NEWS_HEAD [UIImage imageNamed:@"me_news_head"]
#define IMAGE_ME_RECYCLE_BIN [UIImage imageNamed:@"me_recycle_bin"]
#define IMAGE_ME_RECYCLE_BLANK [UIImage imageNamed:@"me_recycle_blank"]
#define IMAGE_ME_REDUCTION [UIImage imageNamed:@"me_reduction"]
#define IMAGE_ME_SHARE [UIImage imageNamed:@"me_share"]
#define IMAGE_ME_SHARE_ICON [UIImage imageNamed:@"me_share_icon"]
#define IMAGE_ME_TRIAL_FEEDBACK [UIImage imageNamed:@"me_trial_feedback"]
#define IMAGE_ME_WEB [UIImage imageNamed:@"me_web"]
#define IMAGE_NETWORKING_STATUS [UIImage imageNamed:@"networking_status"]
#define IMAGE_PHOTO_BACK [UIImage imageNamed:@"photo_back"]
#define IMAGE_PUSH_BG [UIImage imageNamed:@"push_bg"]
#define IMAGE_PUSH_HEAD [UIImage imageNamed:@"push_head"]
#define IMAGE_PUSH_LOGIN_ICON [UIImage imageNamed:@"push_login_icon"]
#define IMAGE_QRCODE_BACK [UIImage imageNamed:@"qrcode_back"]
#define IMAGE_QRCODE_HIGHTLIGHT [UIImage imageNamed:@"qrcode_hightlight"]
#define IMAGE_SCREENSHOT_FEEDBACK [UIImage imageNamed:@"screenshot_feedback"]
#define IMAGE_SCREENSHOT_SHARE [UIImage imageNamed:@"screenshot_share"]
#define IMAGE_SEARCH_ALL [UIImage imageNamed:@"search_all"]
#define IMAGE_SEARCH_ALL_SED [UIImage imageNamed:@"search_all_sed"]
#define IMAGE_SEARCH_EMPTY_ICON [UIImage imageNamed:@"search_empty_icon"]
#define IMAGE_SEARCH_FILE [UIImage imageNamed:@"search_file"]
#define IMAGE_SEARCH_FILE_SED [UIImage imageNamed:@"search_file_sed"]
#define IMAGE_SEARCH_OTHER [UIImage imageNamed:@"search_other"]
#define IMAGE_SEARCH_OTHER_SED [UIImage imageNamed:@"search_other_sed"]
#define IMAGE_SEARCH_PIC [UIImage imageNamed:@"search_pic"]
#define IMAGE_SEARCH_PIC_SED [UIImage imageNamed:@"search_pic_sed"]
#define IMAGE_SECURE_TEXT_ENTRY [UIImage imageNamed:@"secure_text_entry"]
#define IMAGE_SELECH_VIDEO [UIImage imageNamed:@"selech_video"]
#define IMAGE_SELECH_VIDEO_SED [UIImage imageNamed:@"selech_video_sed"]
#define IMAGE_SHARE_BACK [UIImage imageNamed:@"share_back"]
#define IMAGE_SHARE_BACK_LEFT [UIImage imageNamed:@"share_back_left"]
#define IMAGE_SHARE_CANCEL [UIImage imageNamed:@"share_cancel"]
#define IMAGE_SHARE_FILE_ICON [UIImage imageNamed:@"share_file_icon"]
#define IMAGE_SHARE_ICON [UIImage imageNamed:@"share_icon"]
#define IMAGE_SHARE_LINK [UIImage imageNamed:@"share_link"]
#define IMAGE_SHARE_OTHER [UIImage imageNamed:@"share_other"]
#define IMAGE_SHARE_PEO_NUM [UIImage imageNamed:@"share_peo_num"]
#define IMAGE_SHARE_PEOPLE_PROMPT [UIImage imageNamed:@"share_people_prompt"]
#define IMAGE_SHARE_QQ [UIImage imageNamed:@"share_qq"]
#define IMAGE_SHARE_SELECTED [UIImage imageNamed:@"share_selected"]
#define IMAGE_SHARE_WEIXIN [UIImage imageNamed:@"share_weixin"]
#define IMAGE_STARTUP_LOGO [UIImage imageNamed:@"startup_logo"]
#define IMAGE_STARTUP_TITLE [UIImage imageNamed:@"startup_title"]
#define IMAGE_STORAGE_INFO [UIImage imageNamed:@"storage_info"]
#define IMAGE_TABBAR_CHILD [UIImage imageNamed:@"tabbar_child"]
#define IMAGE_TABBAR_ICON_CHILD_SELECTED [UIImage imageNamed:@"tabbar_icon_child_selected"]
#define IMAGE_TABBAR_ICON_FILE [UIImage imageNamed:@"tabbar_icon_file"]
#define IMAGE_TABBAR_ICON_FILE_SELECTED [UIImage imageNamed:@"tabbar_icon_file_selected"]
#define IMAGE_TABBAR_ICON_HOMEPAGE [UIImage imageNamed:@"tabbar_icon_homePage"]
#define IMAGE_TABBAR_ICON_HOMEPAGE_SELECTED [UIImage imageNamed:@"tabbar_icon_homePage_selected"]
#define IMAGE_TABBAR_ICON_HOMEPHOTO [UIImage imageNamed:@"tabbar_icon_homephoto"]
#define IMAGE_TABBAR_ICON_HOMEPHOTO_SELECTED [UIImage imageNamed:@"tabbar_icon_homephoto_selected"]
#define IMAGE_TABBAR_ICON_ME [UIImage imageNamed:@"tabbar_icon_me"]
#define IMAGE_TABBAR_ICON_ME_SELECTED [UIImage imageNamed:@"tabbar_icon_me_selected"]
#define IMAGE_TOAST_ERROR [UIImage imageNamed:@"toast_error"]
#define IMAGE_TOAST_ERROR_SAD_FACE [UIImage imageNamed:@"toast_error_sad_face"]
#define IMAGE_TOAST_SUCCESS [UIImage imageNamed:@"toast_success"]
#define IMAGE_TRY_HEAD_IMAGE [UIImage imageNamed:@"try_head_Image"]
#define IMAGE_UPLOAD_IMAGE [UIImage imageNamed:@"upload_image"]
#define IMAGE_UPLOAD_IMAGE_DELETE [UIImage imageNamed:@"upload_image_delete"]
#define IMAGE_WIFI [UIImage imageNamed:@"wifi"]

#endif /* ESImageDefine_h */
