#import <Foundation/Foundation.h>
#import "ESMemberNameUpdateInfo.h"
#import "ESPersonalCallResult.h"
#import "ESPersonalInfo.h"
#import "ESPersonalInfoResult.h"
#import "ESResponseBaseArrayListAccountInfoResult.h"
#import "ESResponseBaseMemberNameUpdateInfo.h"
#import "ESResponseBasePersonalInfoResult.h"
#import "ESApi.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ESAccountServiceApi: NSObject <ESApi>

extern NSString* kESAccountServiceApiErrorDomain;
extern NSInteger kESAccountServiceApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ESApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// Tries to all user information.
///
/// 
///  code:200 message:"OK"
///
/// @return ESResponseBaseArrayListAccountInfoResult*
-(NSURLSessionTask*) spaceV1ApiMemberListGetWithCompletionHandler: 
    (void (^)(ESResponseBaseArrayListAccountInfoResult* output, NSError* error)) handler;


/// 
/// Tries to update member name information, only admin and yourself has right.
///
/// @param body  (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESResponseBaseMemberNameUpdateInfo*
-(NSURLSessionTask*) spaceV1ApiMemberNameUpdatePostWithBody: (ESMemberNameUpdateInfo*) body
    completionHandler: (void (^)(ESResponseBaseMemberNameUpdateInfo* output, NSError* error)) handler;


/// 
/// Tries to update member information, only admin and yourself has right.
///
/// @param body  (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESResponseBasePersonalInfoResult*
-(NSURLSessionTask*) spaceV1ApiPersonalDomainUpdatePostWithBody: (ESPersonalInfo*) body
    completionHandler: (void (^)(ESResponseBasePersonalInfoResult* output, NSError* error)) handler;


/// 
/// Tries to download personal image, you also can get the image of other member by clientUUID
///
/// @param aoid  (optional)
/// 
///  code:200 message:"OK"
///
/// @return void
-(NSURLSessionTask*) spaceV1ApiPersonalImageGetWithAoid: (NSString*) aoid
    completionHandler: (void (^)(NSError* error)) handler;


/// 
/// 
///
/// @param param 
/// @param file 
/// 
///  code:200 message:"OK"
///
/// @return ESPersonalCallResult*
-(NSURLSessionTask*) spaceV1ApiPersonalImageUpdatePostWithParam: (NSString*) param
    file: (NSData*) file
    completionHandler: (void (^)(ESPersonalCallResult* output, NSError* error)) handler;


/// 
/// Tries to get personal information.
///
/// 
///  code:200 message:"OK"
///
/// @return ESResponseBaseArrayListAccountInfoResult*
-(NSURLSessionTask*) spaceV1ApiPersonalInfoGetWithCompletionHandler: 
    (void (^)(ESResponseBaseArrayListAccountInfoResult* output, NSError* error)) handler;


/// 
/// Tries to update personal name and sign information.
///
/// @param body  (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESResponseBaseArrayListAccountInfoResult*
-(NSURLSessionTask*) spaceV1ApiPersonalInfoUpdatePostWithBody: (ESPersonalInfoResult*) body
    completionHandler: (void (^)(ESResponseBaseArrayListAccountInfoResult* output, NSError* error)) handler;



@end
