#import <Foundation/Foundation.h>
#import "ESAdminBindInfo.h"
#import "ESAdminPasswdInfo.h"
#import "ESResponseBaseAdminBindResult.h"
#import "ESResponseBaseBoolean.h"
#import "ESResponseBasePasswdTryInfo.h"
#import "ESResponseBaseString.h"
#import "ESApi.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ESAdminUserServiceApi: NSObject <ESApi>

extern NSString* kESAdminUserServiceApiErrorDomain;
extern NSInteger kESAdminUserServiceApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ESApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// Tries to create administrator into database.
///
/// @param body  (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESResponseBaseAdminBindResult*
-(NSURLSessionTask*) spaceV1ApiAdminCreatePostWithBody: (ESAdminBindInfo*) body
    completionHandler: (void (^)(ESResponseBaseAdminBindResult* output, NSError* error)) handler;


/// 
/// admin initial status
///
/// @param password 
/// @param flag  (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESResponseBaseBoolean*
-(NSURLSessionTask*) spaceV1ApiAdminInitalStatusPostWithPassword: (NSString*) password
    flag: (NSNumber*) flag
    completionHandler: (void (^)(ESResponseBaseBoolean* output, NSError* error)) handler;


/// 
/// Tries to create administrator into database.
///
/// @param passcode 
/// 
///  code:200 message:"OK"
///
/// @return ESResponseBaseBoolean*
-(NSURLSessionTask*) spaceV1ApiAdminPasswdCheckGetWithPasscode: (NSString*) passcode
    completionHandler: (void (^)(ESResponseBaseBoolean* output, NSError* error)) handler;


/// 
/// Tries to create administrator into database.
///
/// @param body  (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESResponseBaseString*
-(NSURLSessionTask*) spaceV1ApiAdminPasswdSetPostWithBody: (ESAdminPasswdInfo*) body
    completionHandler: (void (^)(ESResponseBaseString* output, NSError* error)) handler;


/// 
/// 撤回对于指定用户的客户端授权信息。该接口支持对任意已存在的用户进行操作（包括管理员）。
///
/// @param userid 指定撤回的用户 id
/// @param passcode passcode (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESResponseBasePasswdTryInfo*
-(NSURLSessionTask*) spaceV1ApiUserClientRevokePostWithUserid: (NSString*) userid
    passcode: (NSString*) passcode
    completionHandler: (void (^)(ESResponseBasePasswdTryInfo* output, NSError* error)) handler;



@end
