#import <Foundation/Foundation.h>
#import "ESPageListResultABContact.h"
#import "ESApi.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ESAddressbookServiceApi: NSObject <ESApi>

extern NSString* kESAddressbookServiceApiErrorDomain;
extern NSInteger kESAddressbookServiceApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ESApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// 获取通信录联系人列表
///
/// @param page 获取列表的页码 (optional)
/// @param pageSize 指定每页的尺寸 (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESPageListResultABContact*
-(NSURLSessionTask*) spaceV1ApiAddressbookContactListGetWithPage: (NSNumber*) page
    pageSize: (NSNumber*) pageSize
    completionHandler: (void (^)(ESPageListResultABContact* output, NSError* error)) handler;



@end
