#import <Foundation/Foundation.h>
#import "ESAppletInfoRes.h"
#import "ESAppletPostReq.h"
#import "ESAppletRegistryInfo.h"
#import "ESAppletRegistryRes.h"
#import "ESAppletReq.h"
#import "ESBaseResultRes.h"
#import "ESCheckAppletResult.h"
#import "ESApi.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ESAppletServiceApi: NSObject <ESApi>

extern NSString* kESAppletServiceApiErrorDomain;
extern NSInteger kESAppletServiceApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ESApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// 校验小程序密钥
///
/// @param appletId 
/// @param appletSecret 
/// @param boxRegKey 
/// 
///  code:200 message:"OK"
///
/// @return ESCheckAppletResult*
-(NSURLSessionTask*) checkAppletResultWithAppletId: (NSString*) appletId
    appletSecret: (NSString*) appletSecret
    boxRegKey: (NSString*) boxRegKey
    completionHandler: (void (^)(ESCheckAppletResult* output, NSError* error)) handler;


/// 
/// 删除小程序
///
/// @param appletId 
/// 
///  code:200 message:"OK"
///
/// @return ESBaseResultRes*
-(NSURLSessionTask*) delAppletWithAppletId: (NSString*) appletId
    completionHandler: (void (^)(ESBaseResultRes* output, NSError* error)) handler;


/// 
/// 下载小程序
///
/// @param body  (optional)
/// 
///  code:200 message:"OK"
///
/// @return void
-(NSURLSessionTask*) downloadAppletWithBody: (ESAppletReq*) body
    completionHandler: (void (^)(NSError* error)) handler;


/// 
/// 获取所有小程序信息
///
/// @param appletId applet_id (optional)
/// 
///  code:200 message:"OK"
///
/// @return NSArray<ESAppletInfoRes>*
-(NSURLSessionTask*) getAppletInfoWithAppletId: (NSString*) appletId
    completionHandler: (void (^)(NSArray<ESAppletInfoRes>* output, NSError* error)) handler;


/// 
/// 增加小程序信息
///
/// @param body  (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESAppletRegistryRes*
-(NSURLSessionTask*) registryAppletWithBody: (ESAppletRegistryInfo*) body
    completionHandler: (void (^)(ESAppletRegistryRes* output, NSError* error)) handler;


/// 
/// 更新小程序信息
///
/// @param appletId 
/// @param body  (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESAppletInfoRes*
-(NSURLSessionTask*) updateAppletWithAppletId: (NSString*) appletId
    body: (ESAppletPostReq*) body
    completionHandler: (void (^)(ESAppletInfoRes* output, NSError* error)) handler;



@end
