#import <Foundation/Foundation.h>
#import "ESArticleReq.h"
#import "ESArticleRes.h"
#import "ESBaseResultRes.h"
#import "ESPageListResultArticleRes.h"
#import "ESApi.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ESArticleServiceApi: NSObject <ESApi>

extern NSString* kESArticleServiceApiErrorDomain;
extern NSInteger kESArticleServiceApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ESApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// 创建文章
///
/// @param body  (optional)
/// 
///  code:200 message:"OK",
///  code:401 message:"Not Authorized",
///  code:403 message:"Not Allowed"
///
/// @return ESArticleRes*
-(NSURLSessionTask*) createArticleWithBody: (ESArticleReq*) body
    completionHandler: (void (^)(ESArticleRes* output, NSError* error)) handler;


/// 
/// 删除文章
///
/// @param articleid 
/// 
///  code:200 message:"OK",
///  code:401 message:"Not Authorized",
///  code:403 message:"Not Allowed"
///
/// @return ESBaseResultRes*
-(NSURLSessionTask*) deleteArticleWithArticleid: (NSNumber*) articleid
    completionHandler: (void (^)(ESBaseResultRes* output, NSError* error)) handler;


/// 
/// 删除文章列表
///
/// @param articleIds  (optional)
/// 
///  code:200 message:"OK",
///  code:401 message:"Not Authorized",
///  code:403 message:"Not Allowed"
///
/// @return ESBaseResultRes*
-(NSURLSessionTask*) deleteArticlesWithArticleIds: (NSArray<NSNumber*>*) articleIds
    completionHandler: (void (^)(ESBaseResultRes* output, NSError* error)) handler;


/// 
/// 获取文章详细信息
///
/// @param articleid 
/// 
///  code:200 message:"OK"
///
/// @return ESArticleRes*
-(NSURLSessionTask*) getArticleDetailWithArticleid: (NSNumber*) articleid
    completionHandler: (void (^)(ESArticleRes* output, NSError* error)) handler;


/// 
/// 获取文章列表
///
/// @param cataId 目录id
/// @param currentPage 当前页
/// @param pageSize 每页数量，最大2000
/// 
///  code:200 message:"OK"
///
/// @return ESPageListResultArticleRes*
-(NSURLSessionTask*) getArticlesWithCataId: (NSNumber*) cataId
    currentPage: (NSNumber*) currentPage
    pageSize: (NSNumber*) pageSize
    completionHandler: (void (^)(ESPageListResultArticleRes* output, NSError* error)) handler;


/// 
/// 修改文章
///
/// @param articleid 
/// @param body  (optional)
/// 
///  code:200 message:"OK",
///  code:401 message:"Not Authorized",
///  code:403 message:"Not Allowed"
///
/// @return ESArticleRes*
-(NSURLSessionTask*) updateArticleWithArticleid: (NSNumber*) articleid
    body: (ESArticleReq*) body
    completionHandler: (void (^)(ESArticleRes* output, NSError* error)) handler;



@end
