#import <Foundation/Foundation.h>
#import "ESResponseBaseListUserEntity.h"
#import "ESResponseBaseUserEntity.h"
#import "ESUserEntity.h"
#import "ESApi.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ESBackupAndRestoreServiceApi: NSObject <ESApi>

extern NSString* kESBackupAndRestoreServiceApiErrorDomain;
extern NSInteger kESBackupAndRestoreServiceApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ESApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// Tries to get all member info. Provide only for file service
///
/// 
///  code:200 message:"OK"
///
/// @return ESResponseBaseListUserEntity*
-(NSURLSessionTask*) spaceV1ApiAccountinfoGetWithCompletionHandler: 
    (void (^)(ESResponseBaseListUserEntity* output, NSError* error)) handler;


/// 
/// Tries to create Member
///
/// @param body  (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESResponseBaseUserEntity*
-(NSURLSessionTask*) spaceV1ApiBackupMemberCreatePostWithBody: (ESUserEntity*) body
    completionHandler: (void (^)(ESResponseBaseUserEntity* output, NSError* error)) handler;


/// 
/// Tries to create Member
///
/// @param body  (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESResponseBaseUserEntity*
-(NSURLSessionTask*) spaceV1ApiBackupMemberUpdatePostWithBody: (ESUserEntity*) body
    completionHandler: (void (^)(ESResponseBaseUserEntity* output, NSError* error)) handler;



@end
