#import <Foundation/Foundation.h>
#import "ESBoxInfosReq.h"
#import "ESBoxInfosRes.h"
#import "ESApi.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ESBoxInfoPresetServiceApi: NSObject <ESApi>

extern NSString* kESBoxInfoPresetServiceApiErrorDomain;
extern NSInteger kESBoxInfoPresetServiceApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ESApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// 设备信息导出接口
///
/// @param body  (optional)
/// 
///  code:200 message:"OK",
///  code:401 message:"Not Authorized",
///  code:403 message:"Not Allowed"
///
/// @return void
-(NSURLSessionTask*) exportWithBody: (ESBoxInfosReq*) body
    completionHandler: (void (^)(NSError* error)) handler;


/// 
/// 模板下载接口
///
/// 
///  code:200 message:"OK",
///  code:401 message:"Not Authorized",
///  code:403 message:"Not Allowed"
///
/// @return void
-(NSURLSessionTask*) tempalteWithCompletionHandler: 
    (void (^)(NSError* error)) handler;


/// 
/// 设备信息导入接口
///
/// @param fileName 文件名称
/// @param file 文件的二进制流 (optional)
/// 
///  code:200 message:"OK",
///  code:401 message:"Not Authorized",
///  code:403 message:"Not Allowed"
///
/// @return ESBoxInfosRes*
-(NSURLSessionTask*) uploadWithFileName: (NSString*) fileName
    file: (NSData*) file
    completionHandler: (void (^)(ESBoxInfosRes* output, NSError* error)) handler;



@end
