#import <Foundation/Foundation.h>
#import "ESBaseResultRes.h"
#import "ESCatalogueReq.h"
#import "ESCatalogueRes.h"
#import "ESApi.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ESCatalogueServiceApi: NSObject <ESApi>

extern NSString* kESCatalogueServiceApiErrorDomain;
extern NSInteger kESCatalogueServiceApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ESApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// 创建目录
///
/// @param body  (optional)
/// 
///  code:200 message:"OK",
///  code:401 message:"Not Authorized",
///  code:403 message:"Not Allowed"
///
/// @return ESCatalogueRes*
-(NSURLSessionTask*) createCataloguesWithBody: (ESCatalogueReq*) body
    completionHandler: (void (^)(ESCatalogueRes* output, NSError* error)) handler;


/// 
/// 删除目录
///
/// @param cataid 
/// 
///  code:200 message:"OK",
///  code:401 message:"Not Authorized",
///  code:403 message:"Not Allowed"
///
/// @return ESBaseResultRes*
-(NSURLSessionTask*) deleteCataloguesWithCataid: (NSNumber*) cataid
    completionHandler: (void (^)(ESBaseResultRes* output, NSError* error)) handler;


/// 
/// 查询节点下所有子目录
///
/// @param cataid 
/// 
///  code:200 message:"OK"
///
/// @return NSArray<ESCatalogueRes>*
-(NSURLSessionTask*) getCataloguesWithCataid: (NSNumber*) cataid
    completionHandler: (void (^)(NSArray<ESCatalogueRes>* output, NSError* error)) handler;


/// 
/// 修改目录
///
/// @param cataid 
/// @param body  (optional)
/// 
///  code:200 message:"OK",
///  code:401 message:"Not Authorized",
///  code:403 message:"Not Allowed"
///
/// @return ESCatalogueRes*
-(NSURLSessionTask*) updateCataloguesWithCataid: (NSNumber*) cataid
    body: (ESCatalogueReq*) body
    completionHandler: (void (^)(ESCatalogueRes* output, NSError* error)) handler;



@end
