#import <Foundation/Foundation.h>
#import "ESApi.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ESDefaultApi: NSObject <ESApi>

extern NSString* kESDefaultApiErrorDomain;
extern NSInteger kESDefaultApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ESApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// 
///
/// 
///  code:200 message:"OK"
///
/// @return NSString*
-(NSURLSessionTask*) spaceHelloResteasyGetWithCompletionHandler: 
    (void (^)(NSString* output, NSError* error)) handler;



@end
