#import <Foundation/Foundation.h>
#import "ESDeviceInfoResult.h"
#import "ESApi.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ESDeviceStorageServiceApi: NSObject <ESApi>

extern NSString* kESDeviceStorageServiceApiErrorDomain;
extern NSInteger kESDeviceStorageServiceApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ESApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// Tries to get storage information.
///
/// @param clientUUID 
/// 
///  code:200 message:"OK"
///
/// @return ESDeviceInfoResult*
-(NSURLSessionTask*) spaceV1ApiDeviceStorageInfoGetWithClientUUID: (NSString*) clientUUID
    completionHandler: (void (^)(ESDeviceInfoResult* output, NSError* error)) handler;



@end
