#import <Foundation/Foundation.h>
#import "ESCopyFileReq.h"
#import "ESDeleteFileReq.h"
#import "ESErrMess.h"
#import "ESHttputilHTTPError.h"
#import "ESModifyFileReq.h"
#import "ESMoveFileReq.h"
#import "ESRsp.h"
#import "ESRspCopyRsp.h"
#import "ESRspDbAffect.h"
#import "ESRspFileInfoForInnerRsp.h"
#import "ESRspFileInfoRsp.h"
#import "ESRspGetListRspData.h"
#import "ESRspUploadRspBody.h"
#import "ESApi.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ESFileApi: NSObject <ESApi>

extern NSString* kESFileApiErrorDomain;
extern NSInteger kESFileApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ESApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 获取压缩图
/// 
///
/// @param uuid uuid
/// 
///  code:200 message:"压缩图",
///  code:404 message:"压缩图尚不存在",
///  code:500 message:"Internal Server Error"
///
/// @return NSURL*
-(NSURLSessionTask*) spaceV1ApiFileCompressedGetWithUuid: (NSString*) uuid
    completionHandler: (void (^)(NSURL* output, NSError* error)) handler;


/// 复制文件接口
/// 复制文件，文件夹，目前复制文件夹可能有bug
///
/// @param varCopyFilesReq 复制文件的请求参数
/// 
///  code:200 message:"返回值"
///
/// @return ESRspCopyRsp*
-(NSURLSessionTask*) spaceV1ApiFileCopyPostWithVarCopyFilesReq: (ESCopyFileReq*) varCopyFilesReq
    completionHandler: (void (^)(ESRspCopyRsp* output, NSError* error)) handler;


/// 删除文件（夹）到回收站接口，支持批量删除
/// 删除文件或者文件夹
///
/// @param deleteId 删除的文件(夹)uuid
/// 
///  code:200 message:"返回值",
///  code:400 message:"Bad Request",
///  code:404 message:"Bad Request"
///
/// @return ESRspDbAffect*
-(NSURLSessionTask*) spaceV1ApiFileDeletePostWithDeleteId: (ESDeleteFileReq*) deleteId
    completionHandler: (void (^)(ESRspDbAffect* output, NSError* error)) handler;


/// 文件下载
/// 文件下载：支持通过 header 传入 Range 参数仅下载文件的指定部分，可以利用该特性实现断点下载，不指定 Range，则下载整个文件。
///
/// @param uuid uuid
/// @param range 指定获取文件的指定部分如：bytes&#x3D;200-1000 (optional)
/// 
///  code:200 message:"整个文件",
///  code:206 message:"Partial Content",
///  code:404 message:"Not Found",
///  code:416 message:"Range Not Satisfiable",
///  code:500 message:"Internal Server Error"
///
/// @return NSURL*
-(NSURLSessionTask*) spaceV1ApiFileDownloadGetWithUuid: (NSString*) uuid
    range: (NSString*) range
    completionHandler: (void (^)(NSURL* output, NSError* error)) handler;


/// 查询文件信息
/// 返回文件信息
///
/// @param uuid 文件(夹)uuid (optional)
/// @param path 文件路径 (optional)
/// @param name 文件名 (optional)
/// 
///  code:200 message:"文件信息"
///
/// @return ESRspFileInfoRsp*
-(NSURLSessionTask*) spaceV1ApiFileInfoGetWithUuid: (NSString*) uuid
    path: (NSString*) path
    name: (NSString*) name
    completionHandler: (void (^)(ESRspFileInfoRsp* output, NSError* error)) handler;


/// 文件列表接口
/// 返回文件列表，
///
/// @param uuid 文件夹uuid (optional)
/// @param isDir 是否筛选文件夹，false为不筛选，true为筛选 (optional)
/// @param page 页码，默认1 (optional)
/// @param pageSize 页码大小，默认10 (optional)
/// @param orderBy 排序,默认为倒序 (optional)
/// @param category 分类,默认为document，video，picture,other（其他）四选一，只有在请求文件分类的时候需要传入，查看全部文件不需要传入 (optional)
/// 
///  code:1005 message:"文件夹不存在",
///  code:200 message:"文件列表"
///
/// @return ESRspGetListRspData*
-(NSURLSessionTask*) spaceV1ApiFileListGetWithUuid: (NSString*) uuid
    isDir: (NSNumber*) isDir
    page: (NSNumber*) page
    pageSize: (NSNumber*) pageSize
    orderBy: (NSString*) orderBy
    category: (NSString*) category
    completionHandler: (void (^)(ESRspGetListRspData* output, NSError* error)) handler;


/// 根据路径获取文件信息接口
/// 根据路径获取文件信息接口
///
/// @param path 文件路径
/// @param name 文件名
/// 
///  code:200 message:"文件信息"
///
/// @return ESRspFileInfoRsp*
-(NSURLSessionTask*) spaceV1ApiFileMetadataGetWithPath: (NSString*) path
    name: (NSString*) name
    completionHandler: (void (^)(ESRspFileInfoRsp* output, NSError* error)) handler;


/// 移动文件（夹）接口，支持文件夹
/// 移动文件或文件夹
///
/// @param moveFilesReq 移动文件的请求参数
/// 
///  code:200 message:"返回值"
///
/// @return ESRspDbAffect*
-(NSURLSessionTask*) spaceV1ApiFileMovePostWithMoveFilesReq: (ESMoveFileReq*) moveFilesReq
    completionHandler: (void (^)(ESRspDbAffect* output, NSError* error)) handler;


/// 获取预览 PDF
/// 
///
/// @param uuid uuid
/// 
///  code:200 message:"预览文件内容",
///  code:404 message:"预览文件尚不存在",
///  code:500 message:"Internal Server Error"
///
/// @return NSURL*
-(NSURLSessionTask*) spaceV1ApiFilePreviewGetWithUuid: (NSString*) uuid
    completionHandler: (void (^)(NSURL* output, NSError* error)) handler;


/// 修改文件（夹）名接口
/// 文件名修改，支持文件夹或者文件
///
/// @param modifyFileReq 文件(夹)uuid和新文件名
/// 
///  code:200 message:"返回值"
///
/// @return ESRspDbAffect*
-(NSURLSessionTask*) spaceV1ApiFileRenamePostWithModifyFileReq: (ESModifyFileReq*) modifyFileReq
    completionHandler: (void (^)(ESRspDbAffect* output, NSError* error)) handler;


/// 搜索文件接口
/// 搜索文件，支持在当前文件夹中搜索,支持模糊搜索。
///
/// @param name 文件名，支持模糊查询，但不支持拼音自动识别
/// @param uuid 当前文件夹uuid，如果传入为空，则全局搜索 (optional)
/// @param category 分类，只有在分类搜索的时候需要传入 (optional)
/// @param page 页码，默认1 (optional)
/// @param pageSize 页码大小，默认10 (optional)
/// @param orderBy 排序,默认为按修改时间倒序 (optional)
/// 
///  code:200 message:"返回文件列表"
///
/// @return ESRspGetListRspData*
-(NSURLSessionTask*) spaceV1ApiFileSearchGetWithName: (NSString*) name
    uuid: (NSString*) uuid
    category: (NSString*) category
    page: (NSNumber*) page
    pageSize: (NSNumber*) pageSize
    orderBy: (NSString*) orderBy
    completionHandler: (void (^)(ESRspGetListRspData* output, NSError* error)) handler;


/// 返回缩略图
/// 获取缩略图
///
/// @param uuid 源文件的uuid
/// 
///  code:200 message:"图片内容",
///  code:400 message:"参数错误",
///  code:404 message:"缩略图尚不存在",
///  code:500 message:"Internal Server Error"
///
/// @return NSURL*
-(NSURLSessionTask*) spaceV1ApiFileThumbGetWithUuid: (NSString*) uuid
    completionHandler: (void (^)(NSURL* output, NSError* error)) handler;


/// 一次性上传整个文件（非断点）
/// 文件上传分两部分：参数 formdata 和文件 formdata， 参数部分为json格式，文件部分为通用的 mime 文件方式。
///
/// @param param 文件参数,json格式，包括filename、path、createTime、modifyTime和md5sum, 其中时间字段为 unix timestamp 整型值，其它为 string 类型
/// @param file 文件数据，按通用文件上传方式编码处理或明文数据
/// 
///  code:200 message:"返回信息，如果code值不为200，则包体部分result无效或为空"
///
/// @return ESRspUploadRspBody*
-(NSURLSessionTask*) spaceV1ApiFileUploadPostWithParam: (NSString*) param
    file: (NSString*) file
    completionHandler: (void (^)(ESRspUploadRspBody* output, NSError* error)) handler;


/// 文件列表接口
/// 返回文件列表，
///
/// @param uuid 文件(夹)uuid (optional)
/// 
///  code:200 message:"文件信息"
///
/// @return ESRspFileInfoForInnerRsp*
-(NSURLSessionTask*) spaceV1ApiInnerFileInfoGetWithUuid: (NSString*) uuid
    completionHandler: (void (^)(ESRspFileInfoForInnerRsp* output, NSError* error)) handler;



@end
