#import <Foundation/Foundation.h>
#import "ESRsp.h"
#import "ESApi.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ESKFileApi: NSObject <ESApi>

extern NSString* kESKFileApiErrorDomain;
extern NSInteger kESKFileApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ESApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// KFile 文件上传
/// 提供根据 key 和 keyType 下载文件
///
/// @param key 文件存储的key值
/// @param keyType 文件的类型
/// 
///  code:200 message:"整个文件",
///  code:404 message:"文件不存在"
///
/// @return NSURL*
-(NSURLSessionTask*) spaceV1ApiKfileDownloadGetWithKey: (NSString*) key
    keyType: (NSString*) keyType
    completionHandler: (void (^)(NSURL* output, NSError* error)) handler;


/// 提供通用的根据 key 和 keyType 存取文件，类似对象存储能力
/// 文件上传分两部分：参数 formdata 和文件 formdata， 参数部分为json格式，文件部分为通用的 mime 文件方式。
///
/// @param param 文件参数,json格式，包括key、fileType、 md5sum 和 expireAt, 其中期望过期时间 expireAt 为 unix timestamp 整型， 其余为string类型
/// @param file 文件数据，按通用文件上传方式编码处理或明文数据
/// 
///  code:200 message:"返回信息，无包体"
///
/// @return ESRsp*
-(NSURLSessionTask*) spaceV1ApiKfileUploadPostWithParam: (NSString*) param
    file: (NSString*) file
    completionHandler: (void (^)(ESRsp* output, NSError* error)) handler;



@end
