#import <Foundation/Foundation.h>
#import "ESMemberCreateInfo.h"
#import "ESMemberUsedStorageResult.h"
#import "ESResponseBaseMemberCreateResult.h"
#import "ESResponseBaseString.h"
#import "ESApi.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ESMemberManageServiceApi: NSObject <ESApi>

extern NSString* kESMemberManageServiceApiErrorDomain;
extern NSInteger kESMemberManageServiceApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ESApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// Tries to create member info into database.
///
/// @param aoId  (optional)
/// @param body  (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESResponseBaseMemberCreateResult*
-(NSURLSessionTask*) spaceV1ApiMemberCreatePostWithAoId: (NSString*) aoId
    body: (ESMemberCreateInfo*) body
    completionHandler: (void (^)(ESResponseBaseMemberCreateResult* output, NSError* error)) handler;


/// 
/// Tries to delete member info from database.
///
/// @param aoid  (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESResponseBaseString*
-(NSURLSessionTask*) spaceV1ApiMemberDeleteDeleteWithAoid: (NSString*) aoid
    completionHandler: (void (^)(ESResponseBaseString* output, NSError* error)) handler;


/// 
/// 获取各个用户所占用空间
///
/// @param aoid 
/// 
///  code:200 message:"OK"
///
/// @return ESMemberUsedStorageResult*
-(NSURLSessionTask*) spaceV1ApiMemberUsedStorageGetWithAoid: (NSString*) aoid
    completionHandler: (void (^)(ESMemberUsedStorageResult* output, NSError* error)) handler;


/// 
/// Tries to get member info from database.
///
/// @param userid 
/// 
///  code:200 message:"OK"
///
/// @return ESResponseBaseMemberCreateResult*
-(NSURLSessionTask*) spaceV1ApiUserClientuuidGetWithUserid: (NSString*) userid
    completionHandler: (void (^)(ESResponseBaseMemberCreateResult* output, NSError* error)) handler;


/// 
/// Tries to get member info from database.
///
/// @param clientUuid 
/// 
///  code:200 message:"OK"
///
/// @return ESResponseBaseMemberCreateResult*
-(NSURLSessionTask*) spaceV1ApiUserGetWithClientUuid: (NSString*) clientUuid
    completionHandler: (void (^)(ESResponseBaseMemberCreateResult* output, NSError* error)) handler;



@end
