#import <Foundation/Foundation.h>
#import "ESCompleteMultipartTaskReq.h"
#import "ESCreateMultipartTaskReq.h"
#import "ESDeleteMultipartTaskReq.h"
#import "ESListMultipartReq.h"
#import "ESRsp.h"
#import "ESRspCompleteMultipartTaskRsp.h"
#import "ESRspCreateMultipartTaskRsp.h"
#import "ESRspListMultipartRsp.h"
#import "ESApi.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ESMultipartApi: NSObject <ESApi>

extern NSString* kESMultipartApiErrorDomain;
extern NSInteger kESMultipartApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ESApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 合并分片上传任务
/// 
///
/// @param requestId 请求id
/// @param object 上传任务参数
/// 
///  code:200 message:"返回信息，如果code值不为200，则包体部分result无效或为空"
///
/// @return ESRspCompleteMultipartTaskRsp*
-(NSURLSessionTask*) spaceV1ApiMultipartCompletePostWithRequestId: (NSString*) requestId
    object: (ESCompleteMultipartTaskReq*) object
    completionHandler: (void (^)(ESRspCompleteMultipartTaskRsp* output, NSError* error)) handler;


/// 创建分片上传任务
/// 
///
/// @param requestId 请求id
/// @param object 创建任务参数
/// 
///  code:200 message:"创建分片任务成功，返回分片任务信息"
///
/// @return ESRspCreateMultipartTaskRsp*
-(NSURLSessionTask*) spaceV1ApiMultipartCreatePostWithRequestId: (NSString*) requestId
    object: (ESCreateMultipartTaskReq*) object
    completionHandler: (void (^)(ESRspCreateMultipartTaskRsp* output, NSError* error)) handler;


/// 删除分片上传任务
/// 
///
/// @param requestId 请求id
/// @param object 删除任务参数
/// 
///  code:200 message:"返回信息，如果code值不为200，则包体部分result无效或为空"
///
/// @return ESRsp*
-(NSURLSessionTask*) spaceV1ApiMultipartDeletePostWithRequestId: (NSString*) requestId
    object: (ESDeleteMultipartTaskReq*) object
    completionHandler: (void (^)(ESRsp* output, NSError* error)) handler;


/// 查询分片上传任务信息
/// 
///
/// @param requestId 请求id
/// @param object 查询任务参数
/// 
///  code:200 message:"返回信息，如果code值不为200，则包体部分result无效或为空"
///
/// @return ESRspListMultipartRsp*
-(NSURLSessionTask*) spaceV1ApiMultipartListGetWithRequestId: (NSString*) requestId
    object: (ESListMultipartReq*) object
    completionHandler: (void (^)(ESRspListMultipartRsp* output, NSError* error)) handler;


/// 上传分片
/// 
///
/// @param requestId 请求id
/// @param end 
/// @param md5sum 
/// @param uploadId 
/// @param object 分片文件数据
/// @param start  (optional)
/// 
///  code:200 message:"返回信息，如果code值不为200，则包体部分result无效或为空"
///
/// @return ESRsp*
-(NSURLSessionTask*) spaceV1ApiMultipartUploadPostWithRequestId: (NSString*) requestId
    end: (NSNumber*) end
    md5sum: (NSString*) md5sum
    uploadId: (NSString*) uploadId
    object: (NSString*) object
    start: (NSNumber*) start
    completionHandler: (void (^)(ESRsp* output, NSError* error)) handler;



@end
