#import <Foundation/Foundation.h>
#import "ESBaseResultRes.h"
#import "ESDownloadFileReq.h"
#import "ESFileReq.h"
#import "ESPageListResultProposalRes.h"
#import "ESProposalReq.h"
#import "ESProposalRes.h"
#import "ESUploadFileRes.h"
#import "ESApi.h"
#import "ESPSPSubdomainInfo.h"
/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ESPlatformProposalManagementServiceApi: NSObject <ESApi>

extern NSString* kESPlatformProposalManagementServiceApiErrorDomain;
extern NSInteger kESPlatformProposalManagementServiceApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ESApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// 文件删除接口
///
/// @param body  (optional)
/// 
///  code:200 message:"OK",
///  code:401 message:"Not Authorized",
///  code:403 message:"Not Allowed"
///
/// @return ESBaseResultRes*
-(NSURLSessionTask*) deleteWithBody: (ESFileReq*) body
    completionHandler: (void (^)(ESBaseResultRes* output, NSError* error)) handler;


/// 
/// 文件下载接口
///
/// @param body  (optional)
/// 
///  code:200 message:"OK",
///  code:401 message:"Not Authorized",
///  code:403 message:"Not Allowed"
///
/// @return void
-(NSURLSessionTask*) downloadWithBody: (ESDownloadFileReq*) body
    completionHandler: (void (^)(NSError* error)) handler;


/// 
/// 文件下载接口
///
/// 
///  code:200 message:"OK"
///
/// @return void
-(NSURLSessionTask*) exportWithCompletionHandler: 
    (void (^)(NSError* error)) handler;


/// 
/// 删除意见反馈
///
/// @param proposalId 
/// 
///  code:200 message:"OK",
///  code:401 message:"Not Authorized",
///  code:403 message:"Not Allowed"
///
/// @return ESBaseResultRes*
-(NSURLSessionTask*) proposalDelWithProposalId: (NSNumber*) proposalId
    completionHandler: (void (^)(ESBaseResultRes* output, NSError* error)) handler;


/// 
/// 查询意见反馈详情
///
/// @param proposalId 
/// 
///  code:200 message:"OK",
///  code:401 message:"Not Authorized",
///  code:403 message:"Not Allowed"
///
/// @return ESProposalRes*
-(NSURLSessionTask*) proposalGetWithProposalId: (NSNumber*) proposalId
    completionHandler: (void (^)(ESProposalRes* output, NSError* error)) handler;


/// 
/// 获取意见反馈列表
///
/// @param currentPage 当前页
/// @param pageSize 每页数量，最大2000
/// 
///  code:200 message:"OK",
///  code:401 message:"Not Authorized",
///  code:403 message:"Not Allowed"
///
/// @return ESPageListResultProposalRes*
-(NSURLSessionTask*) proposalListWithCurrentPage: (NSNumber*) currentPage
    pageSize: (NSNumber*) pageSize
    completionHandler: (void (^)(ESPageListResultProposalRes* output, NSError* error)) handler;


/// 
/// 新增意见反馈
///
/// @param body  (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESProposalRes*
-(NSURLSessionTask*) proposalSaveWithBody: (ESProposalReq*) body
    completionHandler: (void (^)(ESProposalRes* output, NSError* error)) handler;


/// 
/// 更新意见反馈
///
/// @param proposalId 
/// @param body  (optional)
/// 
///  code:200 message:"OK",
///  code:401 message:"Not Authorized",
///  code:403 message:"Not Allowed"
///
/// @return ESProposalRes*
-(NSURLSessionTask*) proposalUpdateWithProposalId: (NSNumber*) proposalId
    body: (ESProposalReq*) body
    completionHandler: (void (^)(ESProposalRes* output, NSError* error)) handler;


/// 
/// 文件上传接口
///
/// @param fileName 文件名称
/// @param isPublish 是否公开 (optional)
/// @param file 文件的二进制流 (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESUploadFileRes*
-(NSURLSessionTask*) uploadWithFileName: (NSString*) fileName
    isPublish: (NSNumber*) isPublish
    file: (NSData*) file
    completionHandler: (void (^)(ESUploadFileRes* output, NSError* error)) handler;


-(NSURLSessionTask*) stunDetail: (NSString*) subdomain
              completionHandler: (void (^)(ESPSPSubdomainInfo* output, NSError* error)) handler;

@end
