#import <Foundation/Foundation.h>
#import "ESCompatibleCheckRes.h"
#import "ESPackageCheckRes.h"
#import "ESApi.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ESPlatformServiceApi: NSObject <ESApi>

extern NSString* kESPlatformServiceApiErrorDomain;
extern NSInteger kESPlatformServiceApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ESApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// 
///
/// @param action  (optional)
/// @param appPkgName  (optional)
/// @param appPkgType  (optional)
/// @param boxPkgName  (optional)
/// @param boxPkgType  (optional)
/// @param curAppVersion  (optional)
/// @param curBoxVersion  (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESPackageCheckRes*
-(NSURLSessionTask*) spaceV1ApiPackageCheckGetWithAction: (NSString*) action
    appPkgName: (NSString*) appPkgName
    appPkgType: (NSString*) appPkgType
    boxPkgName: (NSString*) boxPkgName
    boxPkgType: (NSString*) boxPkgType
    curAppVersion: (NSString*) curAppVersion
    curBoxVersion: (NSString*) curBoxVersion
    completionHandler: (void (^)(ESPackageCheckRes* output, NSError* error)) handler;


/// 
/// 
///
/// @param appPkgName 
/// @param appPkgType 
/// @param boxPkgName 
/// @param boxPkgType 
/// @param curAppVersion 
/// @param curBoxVersion 
/// 
///  code:200 message:"OK"
///
/// @return ESCompatibleCheckRes*
-(NSURLSessionTask*) spaceV1ApiPackageCompatibleGetWithAppPkgName: (NSString*) appPkgName
    appPkgType: (NSObject*) appPkgType
    boxPkgName: (NSString*) boxPkgName
    boxPkgType: (NSObject*) boxPkgType
    curAppVersion: (NSString*) curAppVersion
    curBoxVersion: (NSString*) curBoxVersion
    completionHandler: (void (^)(ESCompatibleCheckRes* output, NSError* error)) handler;



@end
