#import <Foundation/Foundation.h>
#import "ESSubdomainGenResult.h"
#import "ESSubdomainUpdateResult.h"
#import "ESApi.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ESPlatformRegistryServiceApi: NSObject <ESApi>

extern NSString* kESPlatformRegistryServiceApiErrorDomain;
extern NSInteger kESPlatformRegistryServiceApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ESApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// 分发全局唯一的subdomain。
///
/// @param boxRegKey 盒子的注册 key。
/// @param boxUuid 盒子的 uuid。
/// @param effectiveTime 有效期，单位秒，最长7天 (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESSubdomainGenResult*
-(NSURLSessionTask*) subdomainGenWithBoxRegKey: (NSString*) boxRegKey
    boxUuid: (NSString*) boxUuid
    effectiveTime: (NSNumber*) effectiveTime
    completionHandler: (void (^)(ESSubdomainGenResult* output, NSError* error)) handler;


/// 
/// 更新subdomain。幂等设计，建议client失败重试3次。
///
/// @param boxUuid 盒子的 uuid。
/// @param subdomain 子域名，最长100字符
/// @param userId 用户的 id。
/// @param userRegKey 用户的注册 key。
/// 
///  code:200 message:"OK"
///
/// @return ESSubdomainUpdateResult*
-(NSURLSessionTask*) subdomainUpdateWithBoxUuid: (NSString*) boxUuid
    subdomain: (NSString*) subdomain
    userId: (NSString*) userId
    userRegKey: (NSString*) userRegKey
    completionHandler: (void (^)(ESSubdomainUpdateResult* output, NSError* error)) handler;



@end
