#import <Foundation/Foundation.h>
#import "ESPageListResultReservedDomainInfo.h"
#import "ESReservedDomainCreateReq.h"
#import "ESReservedDomainCreateRsp.h"
#import "ESReservedDomainDeleteRsp.h"
#import "ESReservedDomainMatchInfo.h"
#import "ESReservedDomainUpdateReq.h"
#import "ESReservedDomainUpdateRsp.h"
#import "ESApi.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ESPlatformReservedDomainServiceApi: NSObject <ESApi>

extern NSString* kESPlatformReservedDomainServiceApiErrorDomain;
extern NSInteger kESPlatformReservedDomainServiceApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ESApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// 创建保留域名
///
/// @param body  (optional)
/// 
///  code:200 message:"OK",
///  code:401 message:"Not Authorized",
///  code:403 message:"Not Allowed"
///
/// @return ESReservedDomainCreateRsp*
-(NSURLSessionTask*) createWithBody: (ESReservedDomainCreateReq*) body
    completionHandler: (void (^)(ESReservedDomainCreateRsp* output, NSError* error)) handler;


/// 
/// 删除保留域名
///
/// @param regexIds 正则id列表
/// 
///  code:200 message:"OK",
///  code:401 message:"Not Authorized",
///  code:403 message:"Not Allowed"
///
/// @return ESReservedDomainDeleteRsp*
-(NSURLSessionTask*) deleteWithRegexIds: (NSArray<NSNumber*>*) regexIds
    completionHandler: (void (^)(ESReservedDomainDeleteRsp* output, NSError* error)) handler;


/// 
/// 查询某一条保留域名匹配的盒子域名
///
/// @param regexId 正则id
/// 
///  code:200 message:"OK",
///  code:401 message:"Not Authorized",
///  code:403 message:"Not Allowed"
///
/// @return NSArray<ESReservedDomainMatchInfo>*
-(NSURLSessionTask*) queryMatchInfoWithRegexId: (NSNumber*) regexId
    completionHandler: (void (^)(NSArray<ESReservedDomainMatchInfo>* output, NSError* error)) handler;


/// 
/// 查询保留域名
///
/// @param currentPage 当前页
/// @param pageSize 每页数量，最大2000
/// 
///  code:200 message:"OK",
///  code:401 message:"Not Authorized",
///  code:403 message:"Not Allowed"
///
/// @return ESPageListResultReservedDomainInfo*
-(NSURLSessionTask*) queryReservedDomainWithCurrentPage: (NSNumber*) currentPage
    pageSize: (NSNumber*) pageSize
    completionHandler: (void (^)(ESPageListResultReservedDomainInfo* output, NSError* error)) handler;


/// 
/// 修改保留域名
///
/// @param regexId 正则id
/// @param body  (optional)
/// 
///  code:200 message:"OK",
///  code:401 message:"Not Authorized",
///  code:403 message:"Not Allowed"
///
/// @return ESReservedDomainUpdateRsp*
-(NSURLSessionTask*) updateWithRegexId: (NSNumber*) regexId
    body: (ESReservedDomainUpdateReq*) body
    completionHandler: (void (^)(ESReservedDomainUpdateRsp* output, NSError* error)) handler;



@end
