#import <Foundation/Foundation.h>
#import "ESBaseResultRes2.h"
#import "ESDeviceTokenReq.h"
#import "ESDeviceTokenRes.h"
#import "ESPushMessage.h"
#import "ESApi.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ESPlatformPushServiceApi: NSObject <ESApi>

extern NSString* kESPlatformPushServiceApiErrorDomain;
extern NSInteger kESPlatformPushServiceApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ESApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// 广播通知
///
/// @param body  (optional)
/// 
///  code:200 message:"OK",
///  code:401 message:"Not Authorized",
///  code:403 message:"Not Allowed"
///
/// @return ESBaseResultRes2*
-(NSURLSessionTask*) broadcastMessageWithBody: (ESPushMessage*) body
    completionHandler: (void (^)(ESBaseResultRes2* output, NSError* error)) handler;


/// 
/// 注册 device token
///
/// @param body  (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESDeviceTokenRes*
-(NSURLSessionTask*) registryDeviceTokenWithBody: (ESDeviceTokenReq*) body
    completionHandler: (void (^)(ESDeviceTokenRes* output, NSError* error)) handler;



@end
