#import <Foundation/Foundation.h>
#import "ESFeedbackReq.h"
#import "ESFeedbackRes.h"
#import "ESPageListResultQuestionnaireRes.h"
#import "ESQuestionnaireReq.h"
#import "ESQuestionnaireRes.h"
#import "ESApi.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ESPlatformQuestionnaireManagementServiceApi: NSObject <ESApi>

extern NSString* kESPlatformQuestionnaireManagementServiceApiErrorDomain;
extern NSInteger kESPlatformQuestionnaireManagementServiceApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ESApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// 用户提交问卷
///
/// @param body  (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESFeedbackRes*
-(NSURLSessionTask*) feedbackSaveWithBody: (ESFeedbackReq*) body
    completionHandler: (void (^)(ESFeedbackRes* output, NSError* error)) handler;


/// 
/// 获取问卷列表
///
/// @param currentPage 当前页
/// @param pageSize 每页数量，最大2000
/// @param userDomain 用户域名 (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESPageListResultQuestionnaireRes*
-(NSURLSessionTask*) questionnaireListWithCurrentPage: (NSNumber*) currentPage
    pageSize: (NSNumber*) pageSize
    userId: (NSString*) userId
    boxUuid: (NSString*) boxUuid
    completionHandler: (void (^)(ESPageListResultQuestionnaireRes* output, NSError* error)) handler;


/// 
/// 新增问卷
///
/// @param body  (optional)
/// 
///  code:200 message:"OK",
///  code:401 message:"Not Authorized",
///  code:403 message:"Not Allowed"
///
/// @return ESQuestionnaireRes*
-(NSURLSessionTask*) questionnaireSaveWithBody: (ESQuestionnaireReq*) body
    completionHandler: (void (^)(ESQuestionnaireRes* output, NSError* error)) handler;



@end
