#import <Foundation/Foundation.h>
#import "ESBaseResultRes.h"
#import "ESPushMessage.h"
#import "ESApi.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ESPushMessageServiceApi: NSObject <ESApi>

extern NSString* kESPushMessageServiceApiErrorDomain;
extern NSInteger kESPushMessageServiceApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ESApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// 
///
/// @param body  (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESBaseResultRes*
-(NSURLSessionTask*) spaceV1ApiPushMessagePostWithBody: (ESPushMessage*) body
    completionHandler: (void (^)(ESBaseResultRes* output, NSError* error)) handler;



@end
