#import <Foundation/Foundation.h>
#import "ESRecycledPhyDeleteReq.h"
#import "ESRestoreRecycledReq.h"
#import "ESRsp.h"
#import "ESRspDbAffect.h"
#import "ESRspGetListRspData.h"
#import "ESApi.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ESRecycledApi: NSObject <ESApi>

extern NSString* kESRecycledApiErrorDomain;
extern NSInteger kESRecycledApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ESApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 清理回收站
/// 清理回收站，不可恢复，调用返回任务接收成功，实际清理动作为异步。
///
/// @param uuids 删除的文件(或目录) uuid 列表，如果列表为空，则表示清空回收站
/// 
///  code:200 message:"返回值"
///
/// @return ESRsp*
-(NSURLSessionTask*) spaceV1ApiRecycledClearPostWithUuids: (ESRecycledPhyDeleteReq*) uuids
    completionHandler: (void (^)(ESRsp* output, NSError* error)) handler;


/// 回收站文件列表
/// 回收站文件列表
///
/// @param page 页码，默认1 (optional)
/// @param pageSize 页码大小，默认10 (optional)
/// 
///  code:200 message:"返回值"
///
/// @return ESRspGetListRspData*
-(NSURLSessionTask*) spaceV1ApiRecycledListGetWithPage: (NSNumber*) page
    pageSize: (NSNumber*) pageSize
    completionHandler: (void (^)(ESRspGetListRspData* output, NSError* error)) handler;


/// 回收站文件还原
/// 回收站文件还原
///
/// @param restoreFilesReq 文件（夹）uuid
/// 
///  code:200 message:"返回值"
///
/// @return ESRspDbAffect*
-(NSURLSessionTask*) spaceV1ApiRecycledRestorePostWithRestoreFilesReq: (ESRestoreRecycledReq*) restoreFilesReq
    completionHandler: (void (^)(ESRspDbAffect* output, NSError* error)) handler;



@end
