#import <Foundation/Foundation.h>
#import "ESErrMess.h"
#import "ESRsp.h"
#import "ESRspDbAffect.h"
#import "ESRspGetListRspData.h"
#import "ESRspMyShareListRsp.h"
#import "ESRspShareContentRsp.h"
#import "ESRspShareDetailRsp.h"
#import "ESRspShareInitRsp.h"
#import "ESRspShareLinkRsp.h"
#import "ESSetCookieReq.h"
#import "ESShareAgainReq.h"
#import "ESShareCancelReq.h"
#import "ESShareDownloadReq.h"
#import "ESShareLinkReq.h"
#import "ESApi.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ESShareApi: NSObject <ESApi>

extern NSString* kESShareApiErrorDomain;
extern NSInteger kESShareApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ESApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 再次分享
/// 再次分享
///
/// @param shareAgainReq 再次分享请求参数
/// 
///  code:200 message:"返回值"
///
/// @return ESRspShareLinkRsp*
-(NSURLSessionTask*) spaceV1ApiShareAgainPostWithShareAgainReq: (ESShareAgainReq*) shareAgainReq
    completionHandler: (void (^)(ESRspShareLinkRsp* output, NSError* error)) handler;


/// 取消分享
/// 取消分享
///
/// @param shareCancelReq 取消分享请求参数
/// 
///  code:200 message:"返回值"
///
/// @return ESRspDbAffect*
-(NSURLSessionTask*) spaceV1ApiShareCancelPostWithShareCancelReq: (ESShareCancelReq*) shareCancelReq
    completionHandler: (void (^)(ESRspDbAffect* output, NSError* error)) handler;


/// 分享详情
/// 分享详情
///
/// @param shareId 分享ID
/// 
///  code:200 message:"返回值"
///
/// @return ESRspShareDetailRsp*
-(NSURLSessionTask*) spaceV1ApiShareDetailGetWithShareId: (NSString*) shareId
    completionHandler: (void (^)(ESRspShareDetailRsp* output, NSError* error)) handler;


/// 分享文件下载
/// 文件下载：支持通过 header 传入 Range 参数仅下载文件的指定部分，可以利用该特性实现断点下载，不指定 Range，则下载整个文件。
///
/// @param shareDownloadReq 文件uuid
/// @param shareId 分享id
/// @param range 指定获取文件的指定部分如：bytes&#x3D;200-1000 (optional)
/// 
///  code:200 message:"整个文件",
///  code:206 message:"Partial Content",
///  code:404 message:"Not Found",
///  code:416 message:"Range Not Satisfiable",
///  code:500 message:"Internal Server Error"
///
/// @return NSURL*
-(NSURLSessionTask*) spaceV1ApiShareDownloadPostWithShareDownloadReq: (ESShareDownloadReq*) shareDownloadReq
    shareId: (NSString*) shareId
    range: (NSString*) range
    completionHandler: (void (^)(NSURL* output, NSError* error)) handler;


/// 文件列表接口
/// 分享页面调用该进口，可以进入文件夹查看文件
///
/// @param uuid 文件夹uuid
/// @param shareId 分享id
/// @param page 页码，默认1 (optional)
/// @param pageSize 分页大小，默认20 (optional)
/// 
///  code:1005 message:"文件夹不存在",
///  code:200 message:"文件列表"
///
/// @return ESRspGetListRspData*
-(NSURLSessionTask*) spaceV1ApiShareFilelistGetWithUuid: (NSString*) uuid
    shareId: (NSString*) shareId
    page: (NSNumber*) page
    pageSize: (NSNumber*) pageSize
    completionHandler: (void (^)(ESRspGetListRspData* output, NSError* error)) handler;


/// 分享内容
/// 分享内容页面，url中包含shareId 信息，可以在后面有需要时候使用。
///
/// @param shareId 分享id
/// @param extractedCode 提取码 (optional)
/// @param page 页数 (optional)
/// @param pageSize 分页大小，默认20 (optional)
/// 
///  code:200 message:"返回值"
///
/// @return ESRspShareContentRsp*
-(NSURLSessionTask*) spaceV1ApiShareGetWithShareId: (NSString*) shareId
    extractedCode: (NSString*) extractedCode
    page: (NSNumber*) page
    pageSize: (NSNumber*) pageSize
    completionHandler: (void (^)(ESRspShareContentRsp* output, NSError* error)) handler;


/// 我的分享
/// 我的分享
///
/// @param page 页数 (optional)
/// @param pageSize 大小 (optional)
/// 
///  code:200 message:"返回值"
///
/// @return ESRspMyShareListRsp*
-(NSURLSessionTask*) spaceV1ApiShareHistoryGetWithPage: (NSNumber*) page
    pageSize: (NSNumber*) pageSize
    completionHandler: (void (^)(ESRspMyShareListRsp* output, NSError* error)) handler;


/// 跳转到验证提取码页面
/// 该页面需要输入提取码，包含用户昵称，头像等信息
///
/// @param shareId 分享id
/// 
///  code:200 message:"返回值"
///
/// @return ESRspShareInitRsp*
-(NSURLSessionTask*) spaceV1ApiShareInitGetWithShareId: (NSString*) shareId
    completionHandler: (void (^)(ESRspShareInitRsp* output, NSError* error)) handler;


/// 设置Session
/// 校验提取码，并且设置Session，设置成功后跳转到 内容页面
///
/// @param setCookieReq 校验提取码参数
/// 
///  code:200 message:"返回值"
///
/// @return ESRsp*
-(NSURLSessionTask*) spaceV1ApiShareInitPostWithSetCookieReq: (ESSetCookieReq*) setCookieReq
    completionHandler: (void (^)(ESRsp* output, NSError* error)) handler;


/// 生成分享链接
/// 生成分享链接
///
/// @param shareLinkReq 生成链接请求参数
/// 
///  code:200 message:"返回值"
///
/// @return ESRspShareLinkRsp*
-(NSURLSessionTask*) spaceV1ApiShareLinkPostWithShareLinkReq: (ESShareLinkReq*) shareLinkReq
    completionHandler: (void (^)(ESRspShareLinkRsp* output, NSError* error)) handler;


/// 分享者查看自己分享的文件列表
/// 分享者分享多个文件的时候，在我的分享-分享详情点击文件图标的时候可以查看该次分享的所有文件列表
///
/// @param shareId 分享id
/// @param page 页码，默认1 (optional)
/// @param pageSize 分页大小，默认20 (optional)
/// 
///  code:1005 message:"文件夹不存在",
///  code:200 message:"文件列表"
///
/// @return ESRspGetListRspData*
-(NSURLSessionTask*) spaceV1ApiShareOwnFilelistGetWithShareId: (NSString*) shareId
    page: (NSNumber*) page
    pageSize: (NSNumber*) pageSize
    completionHandler: (void (^)(ESRspGetListRspData* output, NSError* error)) handler;


/// 分享文件下载
/// 文件下载：支持通过 header 传入 Range 参数仅下载文件的指定部分，可以利用该特性实现断点下载，不指定 Range，则下载整个文件。
///
/// @param uuids 文件uuid
/// @param shareId 分享id
/// @param range 指定获取文件的指定部分如：bytes&#x3D;200-1000 (optional)
/// 
///  code:200 message:"整个文件",
///  code:206 message:"Partial Content",
///  code:404 message:"Not Found",
///  code:416 message:"Range Not Satisfiable",
///  code:500 message:"Internal Server Error"
///
/// @return NSURL*
-(NSURLSessionTask*) spaceV2ApiShareDownloadGetWithUuids: (NSString*) uuids
    shareId: (NSString*) shareId
    range: (NSString*) range
    completionHandler: (void (^)(NSURL* output, NSError* error)) handler;



@end
