#import <Foundation/Foundation.h>
#import "ESCreateMemberInfo.h"
#import "ESCreateMemberResult.h"
#import "ESCreateMemberTokenInfo.h"
#import "ESCreateTokenResult.h"
#import "ESInviteResult.h"
#import "ESResponseBaseRevokeMemberClientResult.h"
#import "ESRevokeMemberClientInfo.h"
#import "ESApi.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ESSpaceGatewayMemberAuthingServiceApi: NSObject <ESApi>

extern NSString* kESSpaceGatewayMemberAuthingServiceApiErrorDomain;
extern NSInteger kESSpaceGatewayMemberAuthingServiceApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ESApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// 成员接受邀请接口 使用邀请码验证是否是有效邀请，并返回盒子公钥
///
/// @param inviteCode  (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESInviteResult*
-(NSURLSessionTask*) spaceV1ApiGatewayAuthMemberAcceptGetWithInviteCode: (NSString*) inviteCode
    completionHandler: (void (^)(ESInviteResult* output, NSError* error)) handler;


/// 
/// 成员创建接口 使用邀请码（盒子公钥加密）和客户端UUID（盒子公钥加密）、tempEncryptedSecret（盒子公钥加密）、aoId 获取 AuthKey和 box uuid（临时密钥加密）
///
/// @param aoId  (optional)
/// @param body  (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESCreateMemberResult*
-(NSURLSessionTask*) spaceV1ApiGatewayAuthMemberCreatePostWithAoId: (NSString*) aoId
    body: (ESCreateMemberInfo*) body
    completionHandler: (void (^)(ESCreateMemberResult* output, NSError* error)) handler;


/// 
/// 解绑成员客户端。
///
/// @param body  (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESResponseBaseRevokeMemberClientResult*
-(NSURLSessionTask*) spaceV1ApiGatewayAuthRevokeMemberPostWithBody: (ESRevokeMemberClientInfo*) body
    completionHandler: (void (^)(ESResponseBaseRevokeMemberClientResult* output, NSError* error)) handler;


/// 
/// 成员创建 token 接口 使用AuthKey（盒子公钥加密）和客户端UUID（盒子公钥加密）、临时密钥（盒子公钥加密）获取 token
///
/// @param body  (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESCreateTokenResult*
-(NSURLSessionTask*) spaceV1ApiGatewayAuthTokenCreateMemberPostWithBody: (ESCreateMemberTokenInfo*) body
    completionHandler: (void (^)(ESCreateTokenResult* output, NSError* error)) handler;



@end
