#import <Foundation/Foundation.h>
#import "ESCallRequest.h"
#import "ESRealCallResult.h"
#import "ESApi.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ESSpaceGatewayGenericCallServiceApi: NSObject <ESApi>

extern NSString* kESSpaceGatewayGenericCallServiceApiErrorDomain;
extern NSInteger kESSpaceGatewayGenericCallServiceApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ESApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// Tries to handle and forward a space call request to underlying service regarding with specified service and api name.
///
/// @param body  (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESRealCallResult*
-(NSURLSessionTask*) spaceV1ApiGatewayCallPostWithBody: (ESCallRequest*) body
    completionHandler: (void (^)(ESRealCallResult* output, NSError* error)) handler;


/// 
/// Tries to handle and forward a space file download request to underlying service regarding with specified service and api name.
///
/// @param body  (optional)
/// 
///  code:200 message:"OK"
///
/// @return void
-(NSURLSessionTask*) spaceV1ApiGatewayDownloadPostWithBody: (ESCallRequest*) body
    completionHandler: (void (^)(NSError* error)) handler;


/// 
/// Tries to handle and forward a space file upload request to underlying service regarding with specified service and api name.
///
/// @param file 
/// @param callRequest  (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESRealCallResult*
-(NSURLSessionTask*) spaceV1ApiGatewayUploadPostWithFile: (NSData*) file
    callRequest: (NSDictionary<NSString*, NSString*>*) callRequest
    completionHandler: (void (^)(ESRealCallResult* output, NSError* error)) handler;



@end
