#import <Foundation/Foundation.h>
#import "ESResponseBaseAdminInviteResult.h"
#import "ESApi.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ESSpaceAccountAdminInviteServiceApi: NSObject <ESApi>

extern NSString* kESSpaceAccountAdminInviteServiceApiErrorDomain;
extern NSInteger kESSpaceAccountAdminInviteServiceApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ESApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// 管理员发出邀请. 管理员通过call接口调用.
///
/// @param aoId  (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESResponseBaseAdminInviteResult*
-(NSURLSessionTask*) spaceV1ApiAdminInvitePostWithAoId: (NSString*) aoId
    completionHandler: (void (^)(ESResponseBaseAdminInviteResult* output, NSError* error)) handler;



@end
