#import <Foundation/Foundation.h>
#import "ESApi.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ESSpaceGatewayBytesServingFileServiceApi: NSObject <ESApi>

extern NSString* kESSpaceGatewayBytesServingFileServiceApiErrorDomain;
extern NSInteger kESSpaceGatewayBytesServingFileServiceApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ESApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// 
///
/// @param ak  (optional)
/// @param folder  (optional)
/// 
///  code:200 message:"OK"
///
/// @return void
-(NSURLSessionTask*) spaceV1ApiGatewayMfListGetWithAk: (NSString*) ak
    folder: (NSString*) folder
    completionHandler: (void (^)(NSError* error)) handler;


/// 
/// 媒体文件通过 Bytes(https://en.wikipedia.org/wiki/Byte_serving) 访问接口。
///
/// @param fileName 用于指定获取文件的名称，如果使用 betag 或者 uuid 模式，需要加上相应的前缀，例如：betag:{tag}, uuid:{uuid}
/// @param token 用于指定获取文件的 accessToken
/// @param encrypted 用于启用或关闭加密, ture：启用，false：关闭 (optional)
/// @param range 用于指定获取部分文件的范围 (optional)
/// 
///  code:200 message:"OK"
///
/// @return void
-(NSURLSessionTask*) spaceV1ApiGatewayMfTokenFileNameGetWithFileName: (NSString*) fileName
    token: (NSString*) token
    encrypted: (NSNumber*) encrypted
    range: (NSString*) range
    completionHandler: (void (^)(NSError* error)) handler;



@end
