#import <Foundation/Foundation.h>
#import "ESApi.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ESSpaceGatewayHelloServiceApi: NSObject <ESApi>

extern NSString* kESSpaceGatewayHelloServiceApiErrorDomain;
extern NSInteger kESSpaceGatewayHelloServiceApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ESApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// 
///
/// @param content  (optional)
/// @param file  (optional)
/// 
///  code:200 message:"OK"
///
/// @return void
-(NSURLSessionTask*) spaceHelloDownloadGetWithContent: (NSString*) content
    file: (NSString*) file
    completionHandler: (void (^)(NSError* error)) handler;


/// 
/// 
///
/// 
///  code:200 message:"OK"
///
/// @return NSString*
-(NSURLSessionTask*) spaceHelloGetWithCompletionHandler: 
    (void (^)(NSString* output, NSError* error)) handler;


/// 
/// 
///
/// @param fileName  (optional)
/// @param body  (optional)
/// 
///  code:200 message:"OK"
///
/// @return NSString*
-(NSURLSessionTask*) spaceHelloUploadOnePostWithFileName: (NSString*) fileName
    body: (NSData*) body
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;


/// 
/// 
///
/// @param file  (optional)
/// @param fileName  (optional)
/// 
///  code:200 message:"OK"
///
/// @return NSString*
-(NSURLSessionTask*) spaceHelloUploadPostWithFile: (NSData*) file
    fileName: (NSString*) fileName
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;



@end
