#import <Foundation/Foundation.h>
#import "ESResponseBaseCompatibleCheckRes.h"
#import "ESResponseBasePackageCheckRes.h"
#import "ESResponseBaseString1.h"
#import "ESApi.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ESSpaceGatewayVersionCheckingServiceApi: NSObject <ESApi>

extern NSString* kESSpaceGatewayVersionCheckingServiceApiErrorDomain;
extern NSInteger kESSpaceGatewayVersionCheckingServiceApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ESApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// app 版本检查， 转发平台侧 /v1/api/package/check
///
/// @param appName 
/// @param appType 
/// @param version 
/// 
///  code:200 message:"OK"
///
/// @return ESResponseBasePackageCheckRes*
-(NSURLSessionTask*) spaceV1ApiGatewayVersionAppGetWithAppName: (NSString*) appName
    appType: (NSString*) appType
    version: (NSString*) version
    completionHandler: (void (^)(ESResponseBasePackageCheckRes* output, NSError* error)) handler;


/// 
/// 获取 box 当前版本
///
/// 
///  code:200 message:"OK"
///
/// @return ESResponseBaseString1*
-(NSURLSessionTask*) spaceV1ApiGatewayVersionBoxCurrentGetWithCompletionHandler: 
    (void (^)(ESResponseBaseString1* output, NSError* error)) handler;


/// 
/// box 版本检查
///
/// @param appName 
/// @param appType 
/// @param version 
/// 
///  code:200 message:"OK"
///
/// @return ESResponseBasePackageCheckRes*
-(NSURLSessionTask*) spaceV1ApiGatewayVersionBoxGetWithAppName: (NSString*) appName
    appType: (NSString*) appType
    version: (NSString*) version
    completionHandler: (void (^)(ESResponseBasePackageCheckRes* output, NSError* error)) handler;


/// 
/// app 版本检查
///
/// @param appName 
/// @param appType 
/// @param version 
/// 
///  code:200 message:"OK"
///
/// @return ESResponseBaseCompatibleCheckRes*
-(NSURLSessionTask*) spaceV1ApiGatewayVersionCompatibleGetWithAppName: (NSString*) appName
    appType: (NSString*) appType
    version: (NSString*) version
    completionHandler: (void (^)(ESResponseBaseCompatibleCheckRes* output, NSError* error)) handler;



@end
