#import <Foundation/Foundation.h>
#import "ESRspGetListRspData.h"
#import "ESRspSyncFolderRsp.h"
#import "ESSyncDeviceReq.h"
#import "ESApi.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ESSyncApi: NSObject <ESApi>

extern NSString* kESSyncApiErrorDomain;
extern NSInteger kESSyncApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ESApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 同步文件夹创建接口
/// 可以创建同步文件夹
///
/// @param syncDeviceReq 创建同步文件夹请求参数
/// 
///  code:200 message:"返回值"
///
/// @return ESRspSyncFolderRsp*
-(NSURLSessionTask*) spaceV1ApiSyncCreatePostWithSyncDeviceReq: (ESSyncDeviceReq*) syncDeviceReq
    completionHandler: (void (^)(ESRspSyncFolderRsp* output, NSError* error)) handler;


/// 同步文件夹获取接口
/// 可以获取到文件夹的uuid和路径
///
/// @param syncDeviceReq 获取同步文件夹请求参数
/// 
///  code:200 message:"返回值"
///
/// @return ESRspSyncFolderRsp*
-(NSURLSessionTask*) spaceV1ApiSyncFolderPostWithSyncDeviceReq: (ESSyncDeviceReq*) syncDeviceReq
    completionHandler: (void (^)(ESRspSyncFolderRsp* output, NSError* error)) handler;


/// 增量同步信息获取
/// 增量同步信息获取
///
/// @param timestamp 时间戳
/// @param deviceId 设备ID
/// @param path 路径，默认根目录 (optional)
/// 
///  code:200 message:"返回ModifyTime大于上面传入时间戳的文件列表"
///
/// @return ESRspGetListRspData*
-(NSURLSessionTask*) spaceV1ApiSyncSyncedGetWithTimestamp: (NSNumber*) timestamp
    deviceId: (NSString*) deviceId
    path: (NSString*) path
    completionHandler: (void (^)(ESRspGetListRspData* output, NSError* error)) handler;



@end
