#import <Foundation/Foundation.h>
#import "ESAuthorizedTerminalInfo.h"
#import "ESResponseBaseAuthorizedTerminalEntity.h"
#import "ESResponseBaseListAuthorizedTerminalEntity.h"
#import "ESApi.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ESTerminalAutorizationServiceApi: NSObject <ESApi>

extern NSString* kESTerminalAutorizationServiceApiErrorDomain;
extern NSInteger kESTerminalAutorizationServiceApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ESApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// Tries to get authorized terminal information by userId.
///
/// @param body  (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESResponseBaseAuthorizedTerminalEntity*
-(NSURLSessionTask*) spaceV1ApiAuthorizedTerminalInfoDeleteDeleteWithBody: (ESAuthorizedTerminalInfo*) body
    completionHandler: (void (^)(ESResponseBaseAuthorizedTerminalEntity* output, NSError* error)) handler;


/// 
/// Tries to get authorized terminal information by userId.
///
/// @param aoid  (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESResponseBaseListAuthorizedTerminalEntity*
-(NSURLSessionTask*) spaceV1ApiAuthorizedTerminalInfoGetWithAoid: (NSString*) aoid
    completionHandler: (void (^)(ESResponseBaseListAuthorizedTerminalEntity* output, NSError* error)) handler;


/// 
/// Tries to get authorized terminal information by userId.
///
/// @param body  (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESResponseBaseAuthorizedTerminalEntity*
-(NSURLSessionTask*) spaceV1ApiAuthorizedTerminalInfoInsertPostWithBody: (ESAuthorizedTerminalInfo*) body
    completionHandler: (void (^)(ESResponseBaseAuthorizedTerminalEntity* output, NSError* error)) handler;


/// 
/// Tries to get authorized terminal information by userId.
///
/// @param body  (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESResponseBaseAuthorizedTerminalEntity*
-(NSURLSessionTask*) spaceV1ApiAuthorizedTerminalInfoUpdatePostWithBody: (ESAuthorizedTerminalInfo*) body
    completionHandler: (void (^)(ESResponseBaseAuthorizedTerminalEntity* output, NSError* error)) handler;



@end
