#import <Foundation/Foundation.h>
#import "ESAuthorizedTerminalInfo.h"
#import "ESResponseBaseAuthorizedTerminalEntity.h"
#import "ESResponseBaseAuthorizedTerminalResult.h"
#import "ESResponseBaseListAuthorizedTerminalResult.h"
#import "ESApi.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ESTerminalAuthorizationServiceApi: NSObject <ESApi>

extern NSString* kESTerminalAuthorizationServiceApiErrorDomain;
extern NSInteger kESTerminalAuthorizationServiceApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ESApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// Tries to get authorized terminal information by userId.
///
/// @param aoid  (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESResponseBaseListAuthorizedTerminalResult*
-(NSURLSessionTask*) spaceV1ApiTerminalAllInfoGetWithAoid: (NSString*) aoid
    completionHandler: (void (^)(ESResponseBaseListAuthorizedTerminalResult* output, NSError* error)) handler;


/// 
/// Tries to get authorized terminal information by userId.
///
/// @param aoid 
/// @param clientUUID 
/// 
///  code:200 message:"OK"
///
/// @return ESResponseBaseAuthorizedTerminalResult*
-(NSURLSessionTask*) spaceV1ApiTerminalInfoDeleteDeleteWithAoid: (NSString*) aoid
    clientUUID: (NSString*) clientUUID
    completionHandler: (void (^)(ESResponseBaseAuthorizedTerminalResult* output, NSError* error)) handler;


/// 
/// Tries to get authorized terminal information by userId.
///
/// @param aoid 
/// @param clientUUID 
/// 
///  code:200 message:"OK"
///
/// @return ESResponseBaseAuthorizedTerminalResult*
-(NSURLSessionTask*) spaceV1ApiTerminalInfoDeletePostWithAoid: (NSString*) aoid
    clientUUID: (NSString*) clientUUID
    completionHandler: (void (^)(ESResponseBaseAuthorizedTerminalResult* output, NSError* error)) handler;


/// 
/// Tries to get authorized terminal information by userId.
///
/// @param aoid 
/// @param clientUUID  (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESResponseBaseAuthorizedTerminalResult*
-(NSURLSessionTask*) spaceV1ApiTerminalInfoGetWithAoid: (NSString*) aoid
    clientUUID: (NSString*) clientUUID
    completionHandler: (void (^)(ESResponseBaseAuthorizedTerminalResult* output, NSError* error)) handler;


/// 
/// Tries to get authorized terminal information by userId.
///
/// @param body  (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESResponseBaseAuthorizedTerminalEntity*
-(NSURLSessionTask*) spaceV1ApiTerminalInfoInsertPostWithBody: (ESAuthorizedTerminalInfo*) body
    completionHandler: (void (^)(ESResponseBaseAuthorizedTerminalEntity* output, NSError* error)) handler;


/// 
/// Tries to get authorized terminal information by userId.
///
/// @param body  (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESResponseBaseAuthorizedTerminalEntity*
-(NSURLSessionTask*) spaceV1ApiTerminalInfoUpdatePostWithBody: (ESAuthorizedTerminalInfo*) body
    completionHandler: (void (^)(ESResponseBaseAuthorizedTerminalEntity* output, NSError* error)) handler;


/// 
/// Tries to get authorized terminal information by userId.
///
/// @param aoid 
/// @param clientUUID 
/// @param accessTokenClientUUID  (optional)
/// 
///  code:200 message:"OK"
///
/// @return ESResponseBaseAuthorizedTerminalResult*
-(NSURLSessionTask*) spaceV1ApiTerminalLogoutPostWithAoid: (NSString*) aoid
    clientUUID: (NSString*) clientUUID
    accessTokenClientUUID: (NSString*) accessTokenClientUUID
    completionHandler: (void (^)(ESResponseBaseAuthorizedTerminalResult* output, NSError* error)) handler;



@end
