#import <Foundation/Foundation.h>
#import "ESStartDownRes.h"
#import "ESStartUpgradeRes.h"
#import "ESTask.h"
#import "ESUpgradeConfig.h"
#import "ESApi.h"

/**
* EulixOS Platform Server API
* Platform open APIs
*
* OpenAPI spec version: 0.1.0
* Contact: dev-support@eulixos.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ESUpgradeApi: NSObject <ESApi>

extern NSString* kESUpgradeApiErrorDomain;
extern NSInteger kESUpgradeApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ESApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// GET:/upgrade/config 获取盒子当前的升级配置
/// 
///
/// 
///  code:200 message:"OK"
///
/// @return ESUpgradeConfig*
-(NSURLSessionTask*) agentV1ApiUpgradeConfigGetWithCompletionHandler: 
    (void (^)(ESUpgradeConfig* output, NSError* error)) handler;


/// POST:/upgrade/config 设置盒子当前的升级配置
/// 
///
/// @param config 指定升级配置内容
/// 
///  code:200 message:"OK",
///  code:400 message:"Bad Request"
///
/// @return ESUpgradeConfig*
-(NSURLSessionTask*) agentV1ApiUpgradeConfigPostWithConfig: (ESUpgradeConfig*) config
    completionHandler: (void (^)(ESUpgradeConfig* output, NSError* error)) handler;


/// POST:/upgrade/start-down  添加一个下载任务
/// 
///
/// @param down 下载
/// 
///  code:200 message:"OK",
///  code:208 message:"版本已经下载，尚未安装",
///  code:400 message:"不存在新的版本",
///  code:500 message:"失败，稍后再试"
///
/// @return ESTask*
-(NSURLSessionTask*) upgradeV1ApiStartDownPostWithDown: (ESStartDownRes*) down
    completionHandler: (void (^)(ESTask* output, NSError* error)) handler;


/// POST:/upgrade/start-upgrade 开始安装最新版本
/// 
///
/// @param upgrade 安装
/// 
///  code:200 message:"OK",
///  code:400 message:"版本尚未下载，请先下载",
///  code:409 message:"已经有一个任务正在启动",
///  code:500 message:"失败，稍后再试"
///
/// @return ESTask*
-(NSURLSessionTask*) upgradeV1ApiStartUpgradePostWithUpgrade: (ESStartUpgradeRes*) upgrade
    completionHandler: (void (^)(ESTask* output, NSError* error)) handler;


/// POST:/upgrade/status 获取任务状态
/// 
///
/// 
///  code:200 message:"OK",
///  code:400 message:"当前不存在升级或下载任务",
///  code:500 message:"稍后再试"
///
/// @return ESTask*
-(NSURLSessionTask*) upgradeV1ApiStatusGetWithCompletionHandler: 
    (void (^)(ESTask* output, NSError* error)) handler;



@end
